- docs/action-types.md
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> Fix bad apostrophes

- docs/container-action.md
The link to `action-versioning.md` was relative which lead to appending an additional `docs` folder to the current path which linked to `docs/docs/action-versioning.md` instead of `docs/action-versioning.md`.
By adding the leading `/` the link now works correctly.
> Docs: Fix link to the `action-versioning.md` file

- docs/github-package.md
- docs/package-specs.md
- packages/core/README.md
- packages/exec/README.md
- packages/io/README.md
- packages/tool-cache/README.md
There are a bunch of code blocks in the various packages' READMEs and docs without the fancy syntax highlighting that GitHub provides. This is a small change, but I think it has a nice impact 😄 
I'm not sure who to request reviews from - please let me know if there's right person!
> Highlight codeblocks in markdown files

- docs/javascript-action.md
Docs say it's `using:` but it's actually `uses:`.
See this for reference: https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses
> Correct wrong docs

- packages/exec/README.md
a const can't change so this gives syntax errors when trying to reassign them with ` +=` when receiving output
> fix syntax error in output example

- packages/github/src/context.ts
This should simplify webpack configs so we avoid things like #100
> Use readFileSync instead of require

- docs/github-package.md
Noticed when going through this guide that one of the links was missing a `.md`.
> Fix broken link to Javascript Action

- packages/core/README.md
- packages/core/__tests__/lib.test.ts
- packages/core/src/command.ts
- packages/core/src/core.ts
This pull request adds helpers for `group` and `endgroup`.
- Adds `core.startGroup('name')` and `core.endGroup()` for simple commands
- Adds `core.group('name', asyncFn)` for wrapping asynchronous commands
> Core debug

- package-lock.json
- package.json
- packages/github/README.md
- packages/github/src/github.ts
This adds an optional object of Octokit client options to the GitHub constructor. This allows for debugging, API previews, etc.
This PR also bumps TypeScript to 3.6.2 so that I can use the `Omit` type.
> Accept Octokit.Options in the GitHub constructor

- docs/javascript-action.md
For a first time user creating their first action, everything is confusing. They might not know which file they need to update. Adding the filename makes this step easier to follow.
> added file name of action.yml file. 

- docs/javascript-action.md
For someone that doesn't use git all the time, they might not know they need to go into the .gitignore file. The first time I read this I thought the direction was saying to rename the directory !node_modeules. This update just makes the directions a little more clear. A little less friction for someone starting out with actions.
> step 1. was slightly confusing. 

- docs/github-package.md
The word `you're` in the yaml example made the parsing fail, which baffled me for a while. One fix is to use `"` quotes.
> Error in yaml

- packages/core/package.json
- packages/exec/package.json
- packages/github/package.json
- packages/io/package.json
- packages/tool-cache/package.json
This is supported by npm ([docs](https://docs.npmjs.com/files/package.json#repository)). It can help tools like Dependabot figure out what's changed between versions.
> Add 'repository.directory' to package manifests

- .github/ISSUE_TEMPLATE/bug_report.md
Provide an issue template that will help people locate the GitHub Community forum for GitHub Actions.
> Add a bug report issue template

- .github/workflows/unit-tests.yml
setup-node currently outputs:
`##[warning]Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use node-version instead`
> Fix a setup-node warning

- packages/core/README.md
- packages/core/__tests__/lib.test.ts
- packages/core/src/core.ts
In wrapper action, action author uses these 2 methods for sharing information between his action's main-execution and post-execution, this information is only available to this pair of action's executions, other action within the same job won't get it.
Ex: 
In the main execution:
```javascript
core.saveState("pidToKill", 12345);
```
In the post-execution:
```javascript
var pid = core.getState("pidToKill");
process.kill(pid);
```
> add core method to saveState and getState.

- docs/action-versioning.md
We really shouldn't be deleting the tag on the server, creating a new tag, then pushing the new tag to the server (all while the previous tag is deleted). Workflows will fail to run during that time. We can just overwrite the servers tag instead.
> Overwrite tag rather then delete and create

- docs/commands.md
- docs/problem-matchers.md
[Rendered](https://github.com/actions/toolkit/blob/users/thboop/addProblemMatcherdocs/docs/problem-matchers.md)
Resolves #56
> Document Problem Matcher Commands

- docs/commands.md
Using the syntax `::remove-matcher::the-matcher` wasn't working, but after some trial and error `::remove-matcher owner=the-matcher::` did. There's no mention of this on https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions so I'm not sure if this is a feature that's changing or if it was just documented wrong.
> Fix remove-matcher syntax

- packages/tool-cache/src/tool-cache.ts
The default downloadTool implementation strips the filename so when passing it to the extractTar function, it doesn't have a way of knowing the format without manually specifying it. However what the extractTar function arguments meant and how to specify them wasn't clear before reading the source code, so the documentation here got updated to reflect that.
I put the default value of the flags argument into the documentation because it seems to be missing when shown in auto completion when depending on tool-cache.
> tool-cache: clarify that extractTar extracts gzipped tars

- .github/workflows/unit-tests.yml
- package.json
- packages/core/package-lock.json
- packages/exec/README.md
- packages/exec/__tests__/exec.test.ts
- packages/exec/__tests__/scripts/print-args-cmd.cmd
- packages/exec/__tests__/scripts/print-args-sh.sh
- packages/exec/package.json
- packages/exec/src/toolrunner.ts
- packages/tool-cache/package-lock.json
fixes https://github.com/actions/toolkit/issues/218
> toolrunner should which tool

- packages/exec/__tests__/exec.test.ts
Looks like we need longer timeouts, particularly on windows
> Fix test timeouts

- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/src/tool-cache.ts
Fixes these errors when extracting a zip/tar/7z file to a destination folder that does not exist.
tar on macos and linux
```
/bin/tar: /home/runner/work/toolkit/toolkit/packages/tool-cache/__tests__/TEMP/test-
install-tar.gz/not-exist: Cannot open: No such file or directory
```
7z on windows
```
ENOENT: no such file or directory, chdir 'D:\a\toolkit\toolkit\packages\exec\__tests__'
-> 'D:\a\toolkit\toolkit\packages\tool-cache\__tests__\test-install-7z\not-exist'
```
zip on macos
```
There was an error when attempting to execute the process '/usr/bin/unzip'. This may
indicate the process failed to start. Error: spawn /usr/bin/unzip ENOENT
```
fixes #213 
fixes #82
> fix unzip error

- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/src/tool-cache.ts
> overload downloadTool to accept destination path

- packages/core/package.json
- packages/exec/package.json
- packages/github/package.json
- packages/io/package.json
- packages/tool-cache/package.json
I'm using IntelliJ IDEA and IDE couldn't find type definition of packages. I think it is because each `package.json` doesn't contain `types` field, isn't it? Editing files under `node_modules` resolved the issue.
> add: "types" to each package.json

- .github/workflows/unit-tests.yml
Pull requests currently run every workflow twice, on the push to the branch and on the pull request itself. This change limits `push` events to the master branch to avoid this.
> Only run CI on PRs and pushes to master

- package-lock.json
- package.json
- packages/exec/__tests__/exec.test.ts
- packages/exec/src/toolrunner.ts
- packages/io/__tests__/io.test.ts
- packages/tool-cache/src/tool-cache.ts
Updating to TypeScript version 3.7 to allow using [Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and [Nullish Coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing), among other benefits.
`prettier` was updated to allow it to recognize the `??` operator.
With the `prettier` update, it appears print width is determined differently for strings with `${}` variables.
All code changes are purely cosmetic.
> Update to latest TypeScript version

- .github/workflows/unit-tests.yml
we don't need to run module audits on all OSes and ubuntu is the fastest run
> only audit on ubuntu-latest

- packages/glob/__tests__/glob.test.ts
- packages/glob/__tests__/internal-globber.test.ts
- packages/glob/__tests__/internal-pattern-helper.test.ts
- packages/glob/src/glob.ts
- packages/glob/src/internal-glob-options-helper.ts
- packages/glob/src/internal-glob-options.ts
- packages/glob/src/internal-globber.ts
- packages/glob/src/internal-pattern-helper.ts
This change enables multiple patterns
> multiple glob patterns

- packages/core/__tests__/command.test.ts
- packages/core/__tests__/core.test.ts
- packages/core/src/command.ts
> fix command escaping

- packages/github/README.md
> Update readme with type assertion information

- packages/artifact/README.md
- packages/artifact/RELEASES.md
- packages/artifact/__tests__/download-specification.test.ts
- packages/artifact/__tests__/download.test.ts
- packages/artifact/__tests__/util.test.ts
- packages/artifact/additional-information.md
- packages/artifact/package.json
- packages/artifact/src/internal-artifact-client.ts
- packages/artifact/src/internal-config-variables.ts
- packages/artifact/src/internal-contracts.ts
- packages/artifact/src/internal-download-http-client.ts
- packages/artifact/src/internal-download-specification.ts
- packages/artifact/src/internal-utils.ts
Adds the ability to 
- Download a Single Artifact
- Download All artifacts
Also includes
- Documentation for upload and download functions 🎨 [README.md](https://github.com/actions/toolkit/blob/konradpabjan/artifact-download/packages/artifact/README.md) 🎨
- Additional documentation 🖌 [additional-information.md](https://github.com/actions/toolkit/blob/konradpabjan/artifact-download/packages/artifact/additional-information.md) 🖌
Will be used in the v2 versions of `download-artifact` and `upload-artifact`
After these changes the package will be ready to publish 😎
Things missing from this PR that will be added once the package gets published
- Addition to `README.md` in the `src` for toolkit where all the packages get documented
> @actions/artifact download artifacts

- packages/github/package-lock.json
- packages/github/package.json
- packages/github/src/github.ts
Hi,
The purpose of this PR  is to remove the following error.
```
node_modules/@actions/github/lib/github.d.ts:2:8 - error TS2613: Module '"/.../node_modules/@octokit/rest/index"' has no default export. Did you mean to use 'import { Octokit } from "/.../node_modules/@octokit/rest/index"' instead?
2 import Octokit from '@octokit/rest';
~~~~~~~
```
> Use import {Octokit}

- packages/artifact/package-lock.json
- packages/tool-cache/RELEASES.md
- packages/tool-cache/__tests__/retry-helper.test.ts
- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/package.json
- packages/tool-cache/src/retry-helper.ts
- packages/tool-cache/src/tool-cache.ts
Update tool-cache downloadTool() to handle errors from response body stream
related to https://github.com/actions/setup-node/issues/116
> handle response body error

- packages/tool-cache/RELEASES.md
- packages/tool-cache/__tests__/retry-helper.test.ts
- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/package.json
- packages/tool-cache/src/retry-helper.ts
- packages/tool-cache/src/tool-cache.ts
downloadtool should only retry on 500s and 408 and 429
> only retry downloadtool on 500s and 408 and 429

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/download-specification.test.ts
- packages/artifact/__tests__/upload.test.ts
- packages/artifact/__tests__/util.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/artifact-client.ts
- packages/artifact/src/internal/download-specification.ts
- packages/artifact/src/internal/upload-http-client.ts
- packages/artifact/src/internal/utils.ts
- Prepare for 0.3.0 release
- Update `RELEASES.md` with changelog info
- Bump 0.2.0 -> 0.3.0 in `package.json` and `package-lock.json`
-  Storage Quota Error
- During artifact upload, if a user has hit their storage quota, a `403` might be returned when trying to create a new container for an artifact. There is now a clear error message that lets the user know they can't upload any more artifacts because of storage. For more info, see https://github.com/actions/upload-artifact/issues/62#issuecomment-608313373
-  Extra test has been added to `upload.test.ts` to test a `403` response code along with an extra test in `util.test.ts`
- Empty file downloads
- The `v1` action of `download-artifact` has some extra logic when dealing with empty files. You can find it …
> @actions/artifact package updates

- packages/exec/src/exec.ts
`@actions/exec` package exposes `exec` function but does not expose `ExecOptions` for now.
Since `exec` function's option is [big](https://github.com/actions/toolkit/blob/d9347d4ab99fd507c0b9104b2cf79fb44fcc827d/packages/exec/src/interfaces.ts#L5), I want to make the option object in advance with some complicated logic.
For example, let's say to have a function to run a command and whether stdout value is captured or not is controlled by flag:
```typescript
async function runCommand(cmd: string, capture?: boolean) {
let stdout = '';
const options = { listeners: {} };
if (capture) {
options.listeners.stdout = (data) => {
stdout += data.toString();
};
}
await exec(cmd, [], options);
return stdout;
}
```
This code cannot be compiled because we cannot give proper type to `options` variable. …
> exec: Expose ExecOptions interface

- packages/core/__tests__/command.test.ts
- packages/core/__tests__/core.test.ts
- packages/core/src/command.ts
- packages/core/src/core.ts
Users have been encountering friction when trying to use command inputs.
[This commit](https://github.com/actions/toolkit/commit/8b0300129f08728419263b016de8630f1d426d5f#diff-30c957fdb0e7818041c155a0e3ac6e0b) broke some our handling when users don't pass in strings. We re-added that handling and implemented a test for it. 
We also have had a number of users ask for additional input types. 
https://github.com/actions/toolkit/issues/386 -> Set Failed and Error should accept errors
https://github.com/actions/toolkit/issues/370 -> Set Output should format data into strings
This commit resolves those use cases.
Resolves #398, #386, #370
> Be more lenient in accepting command inputs

- .eslintrc.json
- package-lock.json
- package.json
- packages/github/__tests__/github.test.ts
- tsconfig.eslint.json
Resolves #291 
Updates EsLint to get rid of the unsupported typescript warning every time we run it!
To do this, we had to create a separate tsconfig for the linter, as there was a [breaking change](https://github.com/typescript-eslint/typescript-eslint/issues/853#issuecomment-521523708).
> Update eslint to 2.2.7

- docs/commands.md
- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
We added a command to the runner to enable and disable echoing of commands into stdout. This PR adds documentation and a toolkit wrapper for that feature.
Resolves #192
> Add docs and wrapper for "echo" command

- packages/artifact/README.md
- packages/artifact/RELEASES.md
- packages/artifact/__tests__/util.test.ts
- packages/artifact/docs/additional-information.md
- packages/artifact/docs/implementation-details.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/upload-http-client.ts
- packages/artifact/src/internal/utils.ts
Small updates
- Bump package version to `0.3.1` (`RELEASES.MD`, `package.json` and `package-lock.json`)
- This is super small so it doesn't feel right to go straight to `0.4.0`
- Updates to temporary files during artifact upload
- Explicitly call `cleanup` when we are done using temporary files
- Cleanup code a little so that some ugly `.then()` statements aren't needed
- Update comments and some documentation
- Remove spaces as forbidden characters when uploading artifacts
- For some reason I added this earlier, in `v1` this is not a restriction. See the existing code [here](https://github.com/actions/runner/blob/9f78ad3b3428322131eff596e1e5b027f8db6c14/src/Runner.Plugins/Artifact/PublishArtifact.cs#L43)
- When we push `v2-preview` into `master` for `upload-artifact` this extra …
> @actions/artifact 0.3.1 update

- packages/tool-cache/src/manifest.ts
- packages/tool-cache/src/tool-cache.ts
For some actions, like `setup-python` we want to install tool with different architecture.
For example, Python x86 can be installed to Windows Server 2019 so it makes sense to provide ability to override architecture
> Add architecture filter to findFromManifest

- packages/tool-cache/RELEASES.md
- packages/tool-cache/package-lock.json
- packages/tool-cache/package.json
Consume an updated 1.0.8 http-client which had a security issue
Here is [the security issue](https://github.com/actions/http-client/pull/27) that was fixed in the http-client 1.0.8 release
> bump tool-cache's http-client to 1.0.8

- package-lock.json
- package.json
- tsconfig.json
Updating `ts.jest` from version `24.0.2` to `25.4.0`
Gets rid of an annoying message that keeps showing up when running tests: 
```
ts-jest[versions] (WARN) Version 25.1.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
```
Also adding `__mocks__` to this list of excluded `ts` files. This gets rid of an annoying message that also comes up when running artifact tests that use manual mocks: 
```
jest-haste-map: duplicate manual mock found: config-variables
The following files share their name; please delete one of them:
* <rootDir>\packages\artifact\lib\internal\__mocks__\config-variables.js
* …
```
> Update ts-jest to latest version

- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/src/tool-cache.ts
For: tool-cache
This clears up the error messages when the runner does not have a `unzip` or `powershell` binary installed. This can be an issue on self-hosted runners, and makes it easier to track the root cause of the error.
> Check if tool path exists before executing

- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/src/tool-cache.ts
This avoids spamming the log when unzipping large zip files.
> tool-cache: make extract functions quiet by default and more verbose if `core.isDebug` is set

- .gitignore
We really shouldn't be tracking these. They are a generated file on OSX that serve no purpose.
> Ignore DS_Store files.

- packages/github/RELEASES.md
- packages/github/package-lock.json
- packages/github/package.json
- packages/github/src/github.ts
Related to ADR for setting GHE URLs (in c2c-actions)
The toolkit should use the GITHUB_API_URL and GITHUB_GRAPHQL_URL to connect to GHES or Dotcom.
> set base URL for GHES

- packages/tool-cache/package.json
I noticed https://www.npmjs.com/package/@actions/tool-cache was linking to the wrong homepage, this pull request updates the homepage to be the `tool-cache` folder instead of the `exec` folder.
> Update homepage to be tool-cache instead of exec

- README.md
`--save` is deprecated and done by default. Should be removed.
See https://github.com/actions/toolkit/pull/448#discussion_r422217165 and https://github.com/actions/toolkit/pull/448#discussion_r424708066
> Remove --save in README

- .github/workflows/artifact-tests.yml
- packages/artifact/docs/implementation-details.md
- packages/artifact/src/internal/upload-http-client.ts
Fixes weird retry behavior reported here: https://github.com/actions/upload-artifact/issues/71
If there is a connection error or timeout, the readstream should be successfully reset to the beginning so the subsequent retries should not give the same error.
`actions/cache` recently fixed this issue in a PR so this is largely copying over the same fix: https://github.com/actions/cache/pull/305
> Correctly reset chunk during artifact upload on retry

- packages/cache/RELEASES.md
- packages/cache/__tests__/tar.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/cacheUtils.ts
- packages/cache/src/internal/constants.ts
- packages/cache/src/internal/tar.ts
Addresses: https://github.com/actions/toolkit/issues/462
* Long range mode was added to zstd in [v1.3.2](https://github.com/facebook/zstd/releases?after=v1.3.3) but we are still using v1.3.1 in ubuntu-16.04, so only include `--long` filter if zstd version is greater than v1.3.2
* Change to only use zstd on windows when GnuTar is installed due to bug https://github.com/actions/cache/issues/301
> Fix two issues related to using zstd compression

- packages/github/README.md
- packages/github/__tests__/github.proxy.test.ts
- packages/github/__tests__/github.test.ts
- packages/github/package-lock.json
- packages/github/package.json
- packages/github/src/github.ts
- packages/github/src/internal/utils.ts
- packages/github/src/utils.ts
@actions/github is stuck on an older major version of `@octokit/rest` due to the way we extended the class. Let's move away from extending the Octokit class so we don't encounter this again, and move towards the plugin/defaults model all the JS libraries have been using.
This allows us to customize the octokit is a variety of ways, and reuse existing plugins easily.
In particular,  we currently were using `@octokit/rest` which is just @octokit/core with [3 plugins layered on top](https://github.com/octokit/rest.js/blob/master/src/index.ts):
- @octokit/plugin-paginate-rest - provides the paginate function to paginate rest calls
- @octokit/plugin-rest-endpoint-methods - provides the bulk of the rest apis accessible via functions
- @octokit/plugin-request-log - provides additional logging …
> @actions/github v3 using Octokit/core

- packages/github/src/interfaces.ts
To use `context.payload.comment` in TypeScript, we should do `(context.payload as any).comment`. This PR solves the problem.
> Add type of context.payload.comment

- packages/artifact/package.json
- packages/cache/package.json
- packages/core/package.json
- packages/exec/package.json
- packages/github/package.json
- packages/glob/package.json
Related to this npm issue: 
https://github.com/npm/cli/issues/440#issuecomment-552069243
We published a release of `@actions/github` that included a DS_STORE file. It appears that the default .npmignore is overwritten by the files list. So we can add !.DS_Store to this list to ensure we don't publish any more DS_STORE files. 
Tested locally using `npm publish --dry-run` and `npm pack --dry-run`
Resolves #491
> Explicitly exclude DS store files

- .github/workflows/update-github.yaml
- packages/github/package-lock.json
- packages/github/package.json
This automation will create a PR when any of the prod dependencies in actions/github have been updated. This should simplify the process of keeping the action up to date with octokit releases.
Also included is a bump to the versions of these dependencies, created by the  automation.
It runs every sunday at 18:00 UTC
> Setup Weekly Automation to Update @actions/github

- packages/github/src/context.ts
I created a PR because I wanted this feature too.
I've been dealing with the following workaround, but it would be nice to be able to use it in the library.
https://github.com/8398a7/action-slack/blob/v3.1.0/src/client.ts#L143
Resolves: https://github.com/actions/toolkit/issues/371
> Add execution state information

- packages/github/RELEASES.md
- packages/github/package-lock.json
- packages/github/package.json
We are releasing a new version of actions/github. Due to some octokit changes, we need to major version as there are some minor compat breaks. Details can be found in the release notes!
> Add release notes for `actions/github` 4.0.0

- packages/cache/RELEASES.md
- packages/cache/__tests__/downloadUtils.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/downloadUtils.ts
- packages/cache/tsconfig.json
Creates a timer to display download progress every second, including the # of bytes received and the average download speed.  This is intended to provide better visibility into the download, especially for larger caches.
Here's an example restoring a 500 MB cache:
```
##[debug]Archive Path: /home/runner/work/_temp/7ad5a251-5ec2-455f-ad81-d9968ddcad82/cache.tzst
##[debug]Use Azure SDK: true
##[debug]Download concurrency: 8
##[debug]Request timeout (ms): 30000
##[debug]Downloading segment at offset 0 with length 524301052...
Received 171966464 of 524301052 (32.8%), 164.0 MBs/sec
Received 268435456 of 524301052 (51.2%), 127.9 MBs/sec
Received 486539264 of 524301052 (92.8%), 154.6 MBs/sec
Received 524301052 of 524301052 (100.0%), 143.6 MBs/sec
Cache Size: ~500 MB (524301052 B)
/bin/tar …
```
> Display download progress when using Azure Storage SDK

- .gitignore
- packages/artifact/package.json
- packages/cache/package.json
- packages/core/package.json
- packages/exec/package.json
- packages/github/package.json
- packages/glob/package.json
- packages/io/package.json
- packages/tool-cache/package.json
Our audit command is currently failing due to a lerna overflow issue. There's an open issue in lerna [here](https://github.com/lerna/lerna/issues/2384). For now, we should pipe the stdout to a json file, and have stderr display the results of the run.
> Pipe audit results to a json file so lerna does not overflow

- .github/workflows/update-github.yaml
We are standardizing around the email `github-actions@github.com` until we a better way to associate a commit with the actions bot. This PR updates the octokit upgrade job to use that email.
fyi @ericsciple
> Update email in octokit upgrade job

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/downloadUtils.ts
The `segmentSize` calculation was incorrect as it was using the start of the previous segment instead of the start of the current segment, resulting in `419` errors indicating the range is invalid.
> Fix bug downloading large files with the Azure SDK

- .github/workflows/artifact-tests.yml
- .github/workflows/audit.yml
- .github/workflows/cache-tests.yml
- .github/workflows/unit-tests.yml
- .github/workflows/update-github.yaml
- docs/action-types.md
- docs/action-versioning.md
- docs/commands.md
- docs/container-action.md
- docs/problem-matchers.md
- packages/artifact/README.md
- packages/artifact/package.json
- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/package.json
- packages/cache/src/internal/cacheUtils.ts
- packages/core/package.json
- packages/exec/package.json
- packages/github/__tests__/github.proxy.test.ts
- packages/github/__tests__/github.test.ts
- packages/github/package.json
- packages/github/src/context.ts
- packages/glob/package.json
- packages/io/package.json
- packages/tool-cache/__tests__/manifest.test.ts
- packages/tool-cache/package.json
- packages/tool-cache/src/tool-cache.ts
> Set main as the default branch

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/util.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/utils.ts
Client side fix to: https://github.com/github/c2c-actions-service/issues/1337
> @actions/artifact Retry on 413 response

- packages/cache/RELEASES.md
- packages/cache/__tests__/tar.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/tar.ts
See #475 for details.
Closes: https://github.com/actions/cache/issues/326
> Use posix archive format

- packages/artifact/README.md
- packages/artifact/__tests__/upload.test.ts
- packages/artifact/__tests__/util.test.ts
- packages/artifact/src/internal/__mocks__/config-variables.ts
- packages/artifact/src/internal/artifact-client.ts
- packages/artifact/src/internal/config-variables.ts
- packages/artifact/src/internal/contracts.ts
- packages/artifact/src/internal/upload-http-client.ts
- packages/artifact/src/internal/upload-options.ts
- packages/artifact/src/internal/utils.ts
Introducing an option to reduce the default retention period for uploaded artifacts.
Today all artifacts have a 90 days retention value and there is no knob to reduce the value.  We are revamping the experience so we can set custom expiry on individual artifact.
The new minimum value is `1` day.
> Add an option to specify retention days for artifacts

- packages/core/README.md
Resolves: https://github.com/github/c2c-actions-service/issues/1402
Improvements to action logs are now out for everyone! 
https://github.blog/changelog/2020-09-23-github-actions-log-improvements/
One of the new features is proper support for 3/4 bit, 8 bit and 24 bit color. Action authors should have information about how to use this.
This PR adds some documentation to the `core` package README. There is some existing documentation about logging so this felt like the most logical place to add this new information. Colored output works with the normal `console.log` method, but it's best to document it with our `core.info` method.
🖌[Rendered](https://github.com/actions/toolkit/blob/konradpabjan/logs-color-documentation/packages/core/README.md#styling-output) 🖼
There are a bunch of NPM …
> Documentation around colored output in logs

- packages/cache/RELEASES.md
- packages/cache/__tests__/requestUtils.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/constants.ts
- packages/cache/src/internal/requestUtils.ts
Fixes cache to read status code contained in an `HttpClientError` thrown by `http-client` and handle retries correctly.  Fixes https://github.com/actions/toolkit/issues/537
If using one of the standard `get`, `put`, `post`, etc. methods in `http-client`, it returns an `IHttpClientResponse` that contains a status code.  To check if the request was successful or not, we must check the value of the status code.
If using one of the JSON methods (`getJson`, `putJson`, `postJson`, etc.), it will return an `ITypedResponse<T>` if successful.  If the status code is >= 300, it will throw an Error...except for 404 which will return an `ITypedResponse<T>` with a `null` result.
At some point, we updated the cache to use the JSON methods for several calls, but never updated the logic to expect an …
> Handle errors representing non-successful http responses in retry logic

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/cacheHttpClient.ts
`uploadChunk` is not handling non-successful status codes.  As a result, if the upload fails it will still try to seal the cache.  This ultimately fails, but is adding unnecessary calls to the service as well as creating noise in our telemetry.
> Handle non-successful responses from uploadChunk

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/glob/RELEASES.md
- packages/glob/package-lock.json
- packages/glob/package.json
- packages/tool-cache/RELEASES.md
- packages/tool-cache/package-lock.json
- packages/tool-cache/package.json
Currently, none of the toolkit packages use the [commands that are being deprecated on November 16th](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/).
However, they do include other versions of `@actions/core`, that contain that vulnerability even if they aren't invoking it. Let's update these packages to use the latest version.
> Update @actions/core in remaining toolkit packages

- packages/artifact/__tests__/download.test.ts
Removing `jest.spyOn(DownloadHttpClient.prototype, 'pipeResponseToFile')` from the download artifact tests, and using a readable stream object to test `pipeResponseToFile`. Also verifying the destination file size on disk.
This is set up for a follow-up PR with new test cases for truncated responses, https://github.com/actions/toolkit/pull/652.
> Remove spyon, use readable stream to test pipeResponseToFile

- packages/artifact/__tests__/download.test.ts
- packages/artifact/src/internal/download-http-client.ts
- packages/artifact/src/internal/utils.ts
Continuation of https://github.com/actions/toolkit/pull/652
Closes actions/download-artifact#53 and actions/download-artifact#55
We retry when we receive some non success http status code such as 409, 503, etc.  However even if we received a 200 success status code but the response stream were interrupted during download, we should also retry.  
When we stream down the file, we could stream with gzip compression, and if we do, we rely on gzip processing to detect the stream is corrupted.  If the stream is not gzip compressed, we will verify the downloaded file is of the same size specified in `Content-Length` header.
> Retry artifact download when response stream is truncated (continued)

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/cacheUtils.ts
Fixes https://github.com/actions/toolkit/issues/632
> Fix windows cache path

- packages/cache/__tests__/tar.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/tar.ts
- Print cache size when saving cache (similar to restoring)
- Print restore success (similar to saving)
- Print cached file list (if debug logging is enabled)
This makes logs of saving and restoring cache more similar to each other.
Part of https://github.com/actions/cache/issues/471
> Make caching more verbose

- packages/cache/__tests__/tar.test.ts
- packages/cache/src/internal/tar.ts
As I understant this table: https://github.com/actions/virtual-environments#available-environments
And this comment: https://github.com/actions/virtual-environments/issues/1534#issuecomment-745804159
The 20210123 images are the first ones to contain GNU tar and they are at 90%+ rollout progress.
This aims to fix multiple people's issues with caching inside macOS actions:
https://github.com/actions/cache/issues/403
https://github.community/t/bizarre-issue-with-tar-archive-for-macos-build/145377
https://github.com/Cyberbeni/install-swift-tool/issues/69
> Use GNU tar on macOS if available

- README.md
This avoids confusion. ​(At least I thought it was there, so I read the source.)
> Replace find with which in io package description

- packages/io/RELEASES.md
- packages/io/__tests__/io.test.ts
- packages/io/package-lock.json
- packages/io/package.json
- packages/io/src/io.ts
David is the original author. This PR is mainly for #610.
> Add findInPath method to locate all matching executables in the system path

- docs/problem-matchers.md
A number of developers have worked hard to get GH Action Problem Matchers working for a new class of Annotations - to find that they are not displayed on the PR of interest due to restrictions on Annotation counts in GH Actions.
This PR proposes documenting the limitation and making the limitation visible up-front (and hints at some solutions - though better / more complete examples would be welcome).
> Note annotation limits in Problem Matchers documentation

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/exec/src/toolrunner.ts
- tsconfig.json
Bump `@actions/http-client` to the latest version and create a new release fix a proxy related issue that is effecting some larger enterprise customers: https://github.com/actions/http-client/pull/42
> @actions/artifact 0.5.1 release

- .github/workflows/releases.yml
Fixes an issue where npm fails to authenticate when publishing [example](https://github.com/actions/toolkit/actions/runs/723483158)
> Set npmrc to use the NPM Token

- docs/problem-matchers.md
Add detail on one dimension of multi-line match limitations - as I only discovered this after prototyping a Problem Matcher at some expense.
> Note multiline match limitation in Problem Matchers documentation

- packages/io/__tests__/io.test.ts
- packages/io/src/io-util.ts
- packages/io/src/io.ts
less code = fewer bugs ☺️ 
The `recursive` option have been available since Node.js 10.12.0 ([ref](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback)), and since GitHub Actions runs on Node.js 12.x this should always be available.
> Simplify mkdirP implementation

- packages/tool-cache/__tests__/tool-cache.test.ts
- packages/tool-cache/src/tool-cache.ts
This change allows specifying arbitrary headers when downloading items to the toolcache.
This is useful for some URLs that require things like a particular `Accept` header to be present to deliver the right content.
> Allow specifying arbitrary headers when downloading tools to the tool cache.

- packages/core/README.md
- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
Gets the input value of the boolean type in the YAML specification.
The return value is also in boolean type.
ref: https://yaml.org/type/bool.html
close #723
> feat(core): add getBooleanInput function

- packages/cache/__tests__/cacheUtils.test.ts
- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/__tests__/saveCache.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/cacheUtils.ts
- packages/cache/src/internal/downloadUtils.ts
I was going through the code and was a little confused by the `getArchiveFileSizeIsBytes` name because due to `is` it sounded like a Boolean-returning function. I've changed it to something that should be clearer - `getArchiveFileSizeInBytes`
> Fix typo in function name

- CODEOWNERS
Runtime team is going to take over the tool-cache package
> Runtime is gonna take tool-cache

- package-lock.json
- package.json
- packages/github/README.md
- packages/github/RELEASES.md
- packages/github/__tests__/github.proxy.test.ts
- packages/github/__tests__/github.test.ts
- packages/github/package-lock.json
- packages/github/package.json
- This pr updates the base octokit libraries to expose the newly added rest endpoints.
- However, it also changes the definition of the octokit object, the endpoints are now accessed via `octokit.rest.{endpoint}` rather then `octokit.{endpoint}`, so we need to major version this version and ship `@actions/github v5.0.0`
> Release @actions/github v.5.0.0

- packages/github/package-lock.json
- packages/github/package.json
- packages/tool-cache/package-lock.json
This PR fixes the npm audit check by update dependencies in response to a security advisory.
> Update dependencies of tool-cache to fix `npm audit`

- packages/tool-cache/src/tool-cache.ts
Closes #244 
Export version utility functions. Could be used [here](https://github.com/actions/setup-node/blob/9bb7038a073441f1f0c3c33070fc1601a2638b1e/src/installer.ts#L118) as an example.
> Export isExplicitVersion and evaluateVersions

- packages/glob/__tests__/internal-globber.test.ts
- packages/glob/__tests__/internal-pattern.test.ts
- packages/glob/src/internal-globber.ts
- packages/glob/src/internal-pattern.ts
Resolves #268 
Handles an odd case with `Minimatch` that we worked around before that inadvertently would match files when a trailing slash was added.
> Prevent accidental file matching when glob contains trailing slash

- packages/exec/__tests__/exec.test.ts
- packages/exec/__tests__/scripts/stdoutoutputlarge.js
- packages/exec/__tests__/scripts/stdoutputspecial.js
- packages/exec/src/exec.ts
- packages/exec/src/interfaces.ts
- packages/io/src/io.ts
Adds a convenience function go more easily get the output of an exec command. Rather than having to explicitly define listeners in `ExecOptions` this method will return the collected output of `stdOut` and `stdErr` in addition to the exit code. This should make usage a little less awkward in situations where users need the output of an `exec` command. 
Resolves #769
> Add getExecOutput function

- packages/core/README.md
I've found this little formatting typo.
I was uncertain whether to comment the whole line and leave it in the code block or to move it outside of it: I moved it outside because of the code formatting used for `setNatural`
> [core] docs(README): fix minor formatting issue

- packages/tool-cache/__tests__/manifest.test.ts
- packages/tool-cache/src/manifest.ts
Not all Linux distributions have `/etc/lsb-release` file available. If you try to use local runner like https://github.com/nektos/act it fails to perform actions relying on the toolkit. Say [setup-python](https://github.com/actions/setup-python) action can not proceed because of `/etc/lsb-release` missing. It can not determine version of python distribution to setup for a void os version.
There is one more, apparently more widely used, file `/etc/os-release` that contains release version information similar to lsb-release. This pull request adds support for getting os version from `/etc/os-release` file.
> Get linux version from os-release file if available

- .github/workflows/codeql.yml
We already run on PR so we should catch any changes pushed by devs in this repo. Dependabot doesn't have permission to run on push, so we end up failing this job, and its kind of pointless because a pr will just be opened, so lets just skip it.
> Only run codeql on main branch pushes

- packages/exec/src/toolrunner.ts
Line buffer does not work on big strings.
> Fix broken line buffers

- packages/exec/__tests__/exec.test.ts
- packages/exec/__tests__/scripts/stdlineoutput.js
A followup to #773. This test that a very large line can be sent over the `stdline` listener.
> Add test for large stdline output

- packages/glob/src/internal-hash-files.ts
It already returns the empty string, the action author can decide if they want to log or not.
> HashFiles should not create an annotation/warn on no files

- .github/workflows/audit.yml
- package-lock.json
- scripts/audit-allow-list
In https://github.com/actions/toolkit/pull/845 the workflow https://github.com/actions/toolkit/actions/workflows/audit.yml failed because of some known vulnerabilities.
Most of these I fixed with `npm audit fix`.  However, the `lerna` package, which is a dev dependency, needs to be updated ([discussion](https://github.com/actions/toolkit/pull/845#issuecomment-860785826)).  Therefore, I'm changing the workflow to run with `--production`, which excludes dev dependencies.
Sample output:
> Resolve vulnerabilities found by `npm audit`

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
Last version: https://github.com/actions/toolkit/pull/761
Changes since last version:
- https://github.com/actions/toolkit/pull/815 (no change in functionality to `artifact`)
- https://github.com/actions/toolkit/pull/833
> Bump artifact package version to v0.5.2

- packages/cache/src/cache.ts
This is to avoid filling the SSD while saving multiple large caches
Fixes #791
> Cache: Delete temporary archive after upload

- packages/core/README.md
- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
- packages/core/src/utils.ts
Fixes #892
Also adds missing tests for `core.notice`.
Feedback is appreciated, especially whether this fulfills the pull request requirements. In case you already had an internal pull request for #892, or were working locally on it, feel free to reject this pull request.
> Add `file` property to `AnnotationProperties`

- packages/artifact/__tests__/upload.test.ts
- packages/artifact/src/internal/upload-http-client.ts
Named pipes report file size as 0, which leads to reading the whole
content into memory (0 is less than 64K). This adds additional check to
make sure that the passed in path is not a named pipe, and in that case
opts for the create-temp-file-to-gzip code path.
When running on GitHub Actions infrastructure on `windows` node, named
pipes can be created using `mkfifo` from MSYS2. In that case `fs.Stats`s
`isFIFO()` returns `false`, and not `true` as expected. This case is
detected by `process.platform` being `win32` and the passed file having
length of 0.
As a side note, when MSYS2's `mkfifo` is run, a pipe file is created:
```
prw-rw-rw- 1 User None  0 Mar 31 12:58 pipe
```
If `fs.stat` is invoked at this point `ENOENT` error will be thrown. As
soon as the pipe is written to, this pipe file …
> Support upload from named pipes

- packages/artifact/src/internal/status-reporter.ts
Currently the `totalNumberOfFilesToProcess` was reset for each artifact but not the `processedCount` which lead to percentage values higher than 100% when downloading all artifacts. Also resetting the `processedCount` to `0` fixes that and scopes the counts to a single artifact.
Fixes https://github.com/actions/download-artifact/issues/95
Here is another output with > 100% percent in log output https://github.com/campersau/CefSharp/runs/3389459433?check_suite_focus=true#step:2:3. There are two artifacts with 4 files each:
```
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
Total number of files that will be downloaded: 4
Total file count: 4 ---- Processed file #3 (75.0%)
Total number of files that will be …
```
> Reset processedCount when downloading all artifacts

- packages/artifact/src/internal/artifact-client.ts
- packages/artifact/src/internal/contracts.ts
- packages/artifact/src/internal/upload-http-client.ts
- packages/artifact/src/internal/upload-specification.ts
- packages/artifact/src/internal/utils.ts
This fixes a bunch of small things that make the upload process better
- Clarifications around the upload size
- Improved debug logs around gzip behavior
- truncate millisecond time with error message during exponential back-off is in-progress
- Improve logs to be be a bit more verbose 
- Links to how to enable debug logs + link to limitations around gzip behavior
---
Improved logs (with step debugs enabled): https://github.com/konradpabjan/artifact-test/runs/4359261863?check_suite_focus=true
Older logs for comparison: https://github.com/konradpabjan/artifact-test/runs/4266680264?check_suite_focus=true
---
Closes:
https://github.com/actions/upload-artifact/issues/208
More clear error message to close out:
https://github.com/actions/upload-artifact/issues/243
> Updates to logging for artifact uploads

- packages/artifact/__tests__/path-and-artifact-name-validation.test.ts
- packages/artifact/__tests__/util.test.ts
- packages/artifact/src/internal/artifact-client.ts
- packages/artifact/src/internal/path-and-artifact-name-validation.ts
- packages/artifact/src/internal/upload-specification.ts
- packages/artifact/src/internal/utils.ts
Enforce checking for newline characters and carriage returns in the artifact name and file paths that are uploaded
Will close out: https://github.com/actions/upload-artifact/issues/183
- Restructuring some files + tests so that all the code for validating artifact names + paths is in a single file (not in `utils.ts`) 
- Make the error output more readible, the old code would split the message into multiple lines because the actual newline characters were displayed 
- Add tests for `\\r` and `\\n` 
For invalid artifact name: https://github.com/konradpabjan/artifact-test/actions/runs/1527098177
For invalid path: https://github.com/konradpabjan/artifact-test/actions/runs/1527052660
> Check for newlines and carriage return in artifact paths and name

- packages/artifact/__tests__/upload-gzip.test.ts
- packages/artifact/src/internal/upload-gzip.ts
This is an optimization to speed up artifacts uploads for large files that are already compressed.
See this chart for full implementation details: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/implementation-details.md#uploadcompression-flow
For certain types of files that are already compressed, we basically waste a lot of time creating temporary zips that end up being immediately discarded
Test with 2 800000000 byte (0.75GB) artifacts: 1 min 1second
https://github.com/konradpabjan/artifact-test/runs/4434777033?check_suite_focus=true
Test with existing action, the upload doesn't start until you're 1 min in or so. 2 min 22 seconds total so more than a 50% reduction in time.
https://github.com/konradpabjan/artifact-test/runs/4434790411?check_suite_focus=true
> [Artifacts] Exempt certain types of files from gzip compression

- packages/artifact/src/internal/status-reporter.ts
- packages/artifact/src/internal/upload-http-client.ts
While investigating some 503s that can occur during artifact upload, the server reports that certain chunks were missing as part of the upload. The client thinks that all chunks were uploaded so it's unclear where something could be going wrong. This PR changes a few things
- Displays the chunks that were uploaded for all HTTP calls over 8MB (files that are smaller are not uploaded in chunks). Previously only files over 100MB would have any extra information displayed
- Displays the chunk information after each upload call. Previously there was this `largeFileStatus` that was used to display information about large files every 1 second. Within a 1 second period there can be more than 1 chunk uploaded for a file so I've gotten rid of that and every single HTTP call simply gets outputted. …
> [Artifacts] More detailed information for chunked uploads

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/artifact-client.ts
- packages/artifact/src/internal/download-http-client.ts
- packages/artifact/src/internal/status-reporter.ts
Bump package version from 0.5.2 to 0.6.0 in the following files
- `package.json`
- `package-lock.json`
Document all of the changes going in
Some small tweaks that I figured could squeeze into this PR
- Changes `chunk` to `bytes` for output when displaying chunked upload process. It makes more sense for `bytes` since that is the range that is being displayed
Looks like this: https://github.com/konradpabjan/artifact-test/runs/4437446512?check_suite_focus=true
Remove some unnecessary diagnostic output when downloading all artifacts if debug mode is on. Before this would always show up. We only should call this method if there is an error but you can see in the screenshot we would display this even if a 200 response was received
> [Artifacts] Prep for @actions/artifact 0.6.0 release

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
Will help close out: https://github.com/actions/upload-artifact/issues/281 when the changes are synced
> Prep for @actions/artifact 0.6.1 release

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
Updating these dependencies suppresses the dependabot alert for node-fetch we are getting in [actions/cache](https://github.com/actions/cache).
Alert - `node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor`
Affected versions - `< 2.6.7`
Patched Version - `2.6.7`
We'll also need to bump up the patch version on npm registry - https://www.npmjs.com/package/@actions/cache .
> Update ms-rest-js and storage-blog dependencies for cache

- packages/io/__tests__/io.test.ts
This test started failing when `windows-latest` updated to Windows Server 2022 [first failing run](https://github.com/actions/toolkit/runs/4854644455?check_suite_focus=true)
The last successful run was using Windows Server 2019 [last successful run](https://github.com/actions/toolkit/runs/4752740981?check_suite_focus=true)
This PR updates the test to be consistent with other platforms
> Fix test for windows 2022

- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/cache.ts
With the dynamic cache size limit validation on GHES, the validation error should be shown as warning. In this PR we are  fixing error type to Error, so that cache size limit violation is shown as warning( similar to previous error)
> Fix error type so that cache size limit violation is shown as warning( similar to previous error)

- packages/glob/src/glob.ts
- packages/glob/src/internal-hash-files.ts
These changes are needed to enable appropriate use of the `hashFiles` function on the `actions/runner`.
> Added verbose mode in hashFiles

- packages/exec/RELEASES.md
- packages/exec/package-lock.json
- packages/exec/package.json
- packages/glob/RELEASES.md
- packages/glob/package-lock.json
- packages/glob/package.json
This [pr](https://github.com/actions/toolkit/pull/1055) bumped the exec version, but the pr in question was for glob. So this pr reverts that change, and bumps the correct package
> Glob 0.3.0 release

- packages/core/src/core.ts
- packages/core/src/summary.ts
We originally dark shipped this feature to some users as `core.markdownSummary` but since then the feature name has been changed to be "Job Summary". To avoid conflict with our public documentation and to maintain consistency, this'll be `core.summary` going forward.
However, we'll keep `core.markdownSummary` in the API and marked as deprecated for the next release.
Original release:
- https://github.com/actions/toolkit/pull/1059
Rename:
- https://github.com/actions/toolkit/pull/1072
> Add & deprecate old markdownSummary export

- packages/core/RELEASES.md
- packages/core/package-lock.json
- packages/core/package.json
We're deprecating `core.markdownSummary` and exposing `core.summary`.
Relevant issues:
- https://github.com/actions/toolkit/pull/1072
- https://github.com/actions/toolkit/pull/1073
> @actions/core 1.8.0 release

- packages/http-client/RELEASES.md
- packages/http-client/package-lock.json
- packages/http-client/package.json
Fix to help close out https://github.com/actions/toolkit/issues/1083
We'll need to update at least `@actions/core` and `@actions/github` afterwards as well with this new version
> Bump http-client to version 2.0.1

- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/github/package-lock.json
- packages/github/package.json
- packages/tool-cache/package-lock.json
- packages/tool-cache/package.json
Part of fix for https://github.com/actions/toolkit/issues/1083
> Bump @actions/http-client in all packages that use it

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
Adds `x-actions-results-crc64` and `x-actions-results-md5` checksum headers on upload
- https://github.com/actions/toolkit/pull/1063
> @actions/artifact 1.1.0 release

- packages/cache/RELEASES.md
- packages/cache/__tests__/saveCache.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/cache.ts
Fix for [#624](https://github.com/actions/cache/issues/624), below are the changes in the PR- 
- Checking if the cachePaths generated consist of at least one file/directory to cache. Throwing a warning if there are no paths.
- Unit Test cases.
> Avoid saving empty cache when there are no files to cache.

- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/__tests__/saveCache.test.ts
- packages/cache/src/cache.ts
We recently saw due to unavailability of Actions cache service, some of the setup-* start failing because of their caching feature. Ideally from actions-cache team it is recommended to handle cache service error (non-validation) gracefully and not to fail to workflow. This PR moves that dependency to caches packages, so that we will not throw error and throw the error as warning/info to stderr/stdout.
> Graceful handling of error (non-validation one) 

- packages/cache/__tests__/cacheUtils.test.ts
- packages/cache/src/internal/cacheUtils.ts
This PR fixes the [#833](https://github.com/actions/cache/issues/833) issue in actions/cache.
**Issue Summary**: Cache being saved is empty in case of path being current directory or github.workspace. So github.workspace directory can never get cached.
**Root cause**:  The resolvePaths function returns empty since the relative path of the path provided in cache's path param is calculated against the workspace directory itself. 
**Resolution**: We manually add '.' to paths list since the list will be empty in the above scenario.
Feedback is welcome regarding the implementation and possible alternatives. 👀
> Fix Empty Cache save when the path is github workspace directory

- packages/cache/__tests__/tar.test.ts
- packages/cache/src/internal/tar.ts
This PR fixes the issue [809](https://github.com/actions/cache/issues/809).
Cache save/restore failing on self-hosted EC2 runners running Amazon Linux 2.
Root Cause:
- Tar is failing to recognise flags passed to zstd(eg. `-T0`)  causing no such file or directory error.
- The flags are conflicting with tar flags causing an incorrect command to be formed in case of tar version <= 1.26. This command fails with exit code 2 causing cache save/restore to fail.
Explanation:
Currently, the tar command that is executed is in the form:
`usr/bin/tar --use-compress-program zstd -d -xf`
Here the `-d` is a flag to zstd but gets read as a flag to tar. For zstd  `-d` is decompress. For tar `-d` is diff.
For tar version >= 1.27 this works. Two probable reasons(not tested):
1. The flag gets read as tar’s …
> Move zstd from flags to equivalent aliases

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
This PR aims to release a new toolkit version `v3.0.1` with the following changes:
Bugfixes 🐞 : 
- Fix [#809](https://github.com/actions/cache/issues/809) in actions/cache repo
- Fix [#833](https://github.com/actions/cache/issues/833) in actions/cache repo
I need feedback regarding anything else that needs to be taken care of while releasing a new version. I have been following instructions from [here](https://github.com/github/c2c-actions/blob/main/docs/publishing-first-party-npm-packages.md) 🙇
> Fix #809 and #833 in actions/cache. Bump version for NPM package actions/cache to v3.0.1

- package-lock.json
- package.json
- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
Recently, `npm audit` started failing due to a security vulnerability in lerna. This is a dev dependency, but lets get it updated to fix the issue!
> Update lerna dependency.

- packages/cache/README.md
- packages/cache/RELEASES.md
- packages/cache/__tests__/options.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/options.ts
Added an env var `SEGMENT_DOWNLOAD_TIMEOUT_MINS` that overrides the 1 hour default timeout for decreasing the cache download timeout.
[A successful run ](https://github.com/bbq-beets/test-cache-load/actions/runs/2865816461)
> Added custom user inputted timeout

- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/cache/package-lock.json
- packages/core/package-lock.json
- packages/github/package-lock.json
- packages/glob/package-lock.json
- packages/glob/package.json
- packages/http-client/package-lock.json
- packages/tool-cache/package-lock.json
- scripts/audit-allow-list
- Our tools audits are currently failing to a known [`parse-url < 8.1.0` vulnerability](https://github.com/advisories/GHSA-j9fq-vwqv-2fm2). `parse-url` is a Lerna dependency and the issue [has been reported](https://github.com/lerna/lerna/issues/3312).
- Some of the internal dependencies were outdate, causing the audit to fail
> Resolve auditing issues

- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
Fixed #1186
`core.getInput` is [trimming whitespace](https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L17) by default, but `core.getMultilineInput` is not.
Also, `core.getMultilineInput` ignores `trimWhitespace` option.
This pull request has been fixed so that `core.getMultilineInput` will trim whitespace in the same way as `core.getInput`.
> fix(core): `getMultilineInput` not trimming whitespace

- packages/core/__tests__/core.test.ts
- packages/core/src/core.ts
- packages/core/src/file-command.ts
This adds support for the file command version of `save-state` and `set-output` that are being added to the runner in [#2118](https://github.com/actions/runner/pull/2118).
In the case that these commands are being used on a runner that doesn't support the file-command versions they will fallback to the pre-existing workflow commands.
> Add save-state and set-output file commands

- packages/core/RELEASES.md
- packages/core/package-lock.json
- packages/core/package.json
- `saveState` and `setOutput` now use environment files if available [#1178](https://github.com/actions/toolkit/pull/1178)
- `getMultilineInput` now correctly trims whitespace by default [#1185](https://github.com/actions/toolkit/pull/1185)
> @actions/core 1.10.0 release

- packages/github/src/utils.ts
Certain plugins override the various `OctokitOptions`. Exporting the defaults allows actions that use plugins to inspect the default options and keep them / merge them with their plugin's options if desired.
> Export default octokit options

- packages/cache/README.md
Updating this link -> ["Caching dependencies to speed up workflows"](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) in packages/cache/README.md
> fix README broken link to dep caching

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
Update @action/cache package to use the version `1.10.0` of @actions/core.
> Patch @actions/cache to use @action/core version 1.10.0

- packages/cache/RELEASES.md
Fixed environment variable in release docs. `SEGMENT_DOWNLOAD_TIMEOUT_MIN` has been replaced with `SEGMENT_DOWNLOAD_TIMEOUT_MINS`
> Fixed environment variable in the docs.

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
Upgraded actions/cache version to 3.0.6 to fix compatibility issue with ESM [#1208](https://github.com/actions/toolkit/issues/1208)
> Upgraded actions/cache version to 3.0.6

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
This change is made for beta release of cache package. Beta is used so as to not break any existing usage of cache.
Add support for gnu tar and zstd as default and bsd tar and zstd as fallback on windows
`3.1.0-beta.1`
> Update for beta release of cache package

- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/internal/cacheHttpClient.ts
This would make sure that caches done previously using `gzip` are restorable but any new caches or restore done using restore keys would be saved using `zstd` on windows if available.
When cache not found on windows and compression method is not `gzip` then search again with `gzip`. If cache found with `gzip` compression cache version then continue as usual else throw error.
> Add fallback to gzip compression if cache not found

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
This adds support for fallback to gzip if old cache is present on windows.
> Release 3.1.0-beta.2 cache package

- .github/workflows/cache-windows-test.yml
- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/__tests__/tar.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/tar.ts
Fix known issue with gzip fallback and bsd tar + zstd combination. 
- gzip fallback was failing as getCacheEntry return null when cache not found and throw no error.
- bsd tar + zstd was failing as `exec.exec` doesn't support `&&` so passed commands through `cmd` for that case only as suggested [here](https://github.com/actions/toolkit/issues/461)
> Fix known issues for cache

- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/contracts.d.ts
This PR should show cache version details on cache miss. Sample test workflow run: [here](https://github.com/bbq-beets/test-zstd/actions/runs/3710689378/jobs/6290420326#step:7:52)
> Add logs for cache version on miss

- .github/workflows/cache-windows-test.yml
- packages/cache/__tests__/tar.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/internal/tar.ts
There were few issues which came up during internal bugbash:
1. With debug logs on restore was failing saying `zstd: cache.tar already exists; not overwritten:`. 
Possible solutions:
- Add `--force` to zstd command. Docs say that they overwrite the file with this.
- Delete `cache.tar` file after every list, create and extract operation
**Final solution:** Add --force to zstd command as problem is seen when `list` runs which happen in debug mode thus justifying extra time taken in deleting and creating `cache.tar` file using --force.
3. Change debug log to info log when falling back to gzip for restoration of cache on windows.
> Address bugbash issues

- packages/artifact/src/internal/upload-gzip.ts
These files are already compressed with zstd - no need to attempt re-compression.
> [artifact] exempt .tar.zst files from compression

- packages/core/src/core.ts
Just that, I was using `core` and checking the docs when I noticed the annotation typo
> Fix typo in AnnotationProperties doc

- packages/artifact/src/internal/upload-gzip.ts
The promise's `reject` function currently isn't actually being called in `packages/artifact/src/internal/upload-gzip.ts::createGZipFileOnDisk` in the event of an error. This fixes that by simply calling `reject` with the `error` from the context as argument.
---
Note: I found out about this mistake through [LGTM.com](https://lgtm.com/projects/g/actions/toolkit/snapshot/8ef45a3bfd72f2e0a37a2f819374d6342215d650/files/packages/artifact/src/internal/upload-gzip.ts?sort=name&dir=ASC&mode=heatmap). After patching the problem I noticed this repository also [uses the CodeQL Action](https://github.com/actions/toolkit/blob/c5278cdd088a8ed6a87dbd5c80d7c1ae03beb6e5/.github/workflows/codeql.yml) - and it even [looks like it's reporting this problem](https://github.com/actions/toolkit/runs/7039442930?ch …
> Fix reject call in packages/artifact's upload-zip.ts

- packages/core/README.md
Change the `core.error` documentation to say that it won't automatically fail the action. This matches the existing example in the "logging" section.
Fixes #902
> core: Update "core.error" documentation

- packages/artifact/__tests__/upload-gzip.test.ts
- packages/artifact/src/internal/upload-gzip.ts
Extended the gzip compression exception list with the addition of the extensions recognized by [GNU Tar](https://git.savannah.gnu.org/cgit/tar.git/tree/src/suffix.c?h=release_1_34#n31).
> [Artifacts] Add more extensions to the gzip compression exception list

- packages/artifact/src/internal/artifact-client.ts
`setup` is a noun. The verb phrase is `set up` and its past tense is `set up`.
> Grammar: set up

- packages/glob/__tests__/hash-files.test.ts
- packages/glob/src/glob.ts
- packages/glob/src/internal-hash-files.ts
Follow up work to allow the runner to use the hashFiles implementation in glob
> Pass in the current workspace as a parameter to hashFiles

- packages/cache/__tests__/tar.test.ts
- packages/cache/src/internal/tar.ts
b2d865f18051b21447 introduced a call to exportVariable() to export the MSYS env var, which configures the symlink strategy for MSYS2/cygwin binaries it calls.
By setting the env var globally, this also changes the behaviour of other MSYS2 using tools in a CI job, and also overrides MSYS configuration set by the user, which I think was not intended.
To avoid this leakage set the MSYS env var only for the commands which @actions/cache calls.
Fixes #1312
> Don't set the MSYS env var globally

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
This brings fix for not setting MSYS env variable globally: https://github.com/actions/toolkit/pull/1329
> Release patch version update for cache

- packages/http-client/__tests__/proxy.test.ts
- packages/http-client/src/proxy.ts
The behaviour of the `no_proxy` environmental variable is [famously inconsistent](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/), but this change should follow how it usually works (i.e., that `no_proxy=domain.com` matches its subdomains, such as `some.domain.com`). 
Resolves #1172
> Standardize behaviour of no_proxy environmental variable

- packages/http-client/__tests__/proxy.test.ts
- packages/http-client/src/proxy.ts
Requests to localhost should not be proxied (if the proxy is on another device / network, the proxied request targeting 'localhost' will likely be lost)
The [runner](https://github.com/actions/runner/blob/5421fe3f7107f770c904ed4c7e506ae7a5cde2c2/src/Runner.Sdk/RunnerWebProxy.cs#L203) also ignores loopback IPs
[Golang as well](https://go.dev/src/vendor/golang.org/x/net/http/httpproxy/proxy.go?s=4195:4265#:~:text=if%20ip.IsLoopback,%7D)
> Bypass proxy on loopback IPs (localhost, 127.*, ::1 etc)

- packages/http-client/RELEASES.md
- packages/http-client/package.json
Preparing release of proxy changes from
https://github.com/actions/toolkit/pull/1355
https://github.com/actions/toolkit/pull/1361
https://github.com/actions/toolkit/pull/1223
> Bump http-client to version 2.1.0

- packages/cache/RELEASES.md
- packages/cache/__tests__/options.test.ts
- packages/cache/__tests__/restoreCache.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/cache.ts
- packages/cache/src/options.ts
This PR adds a `lookupOnly` option to the cache restore function.
It can be used to check if a cache exists without the need to download it.
Especially useful if e.g. dependency install and actual tests are split across multiple jobs. If the cache restore step for the dependency install has an exact hit, the remaining steps in the job can be skipped. Similarly if the cache is created from scratch and it's just necessary to know if a cache entry already exists.
Would help address
https://github.com/actions/cache/issues/901
https://github.com/actions/cache/issues/831
https://github.com/actions/cache/discussions/1020#discussioncomment-4332778
https://github.com/actions/cache/discussions/1020#discussioncomment-4341251
Alternative to #1207
CC: @kotewar
> Add cache restore `lookupOnly` option

- packages/cache/RELEASES.md
- packages/cache/__tests__/options.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/downloadUtils.ts
- packages/cache/src/options.ts
- packages/cache/tsconfig.json
This PR updates the blob storage client to v12.13.0 which is the latest to accommodate the latest SDK changes in cache library.
Also updated the typescript version because the [builds](https://github.com/actions/toolkit/actions/runs/4343131738/jobs/7584792497) were failing and azure sdk [uses](https://github.com/Azure/azure-sdk-for-js/commit/526926acc6b089b0e199c54a48bab4afc7e052e1) typescript 4.8.0
> Updating blob storage client to 12.13.0 in actions/cache

- packages/http-client/__tests__/auth.test.ts
- packages/http-client/__tests__/basics.test.ts
- packages/http-client/__tests__/headers.test.ts
- packages/http-client/__tests__/keepalive.test.ts
- packages/http-client/__tests__/proxy.test.ts
httpbin timeouts are causing our http-client tests to timeout too, this changes httpbin to postman-echo (Postman now also owns httpbin).
> Use postman-echo to replace httpbin

- docs/commands.md
- packages/core/__tests__/core.test.ts
As a follow up to https://github.com/actions/toolkit/issues/1421 we've conducted testing that proved that `setSecret` does in fact mask multi line secrets (and so does `::add-mask::` as long as a multi-line string is escaped). This updates the docs to reflect that and adds a test to ensure `setSecret` does escape the string it's being passed.
> Update docs for setSecret

- .eslintrc.json
- packages/cache/RELEASES.md
- packages/cache/__tests__/cacheHttpClient.test.ts
- packages/cache/__tests__/options.test.ts
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/internal/cacheHttpClient.ts
- packages/cache/src/internal/downloadUtils.ts
- packages/cache/src/options.ts
This PR introduces a new default option for download from the Actions Cache. The new option uses the Actions HTTP Client with concurrent downloads from Blob storage, similar to how the Azure SDK works, except this includes much more granular control over timing out downloads during the initial response and while consuming the full response stream. This should once and for all address the issues seen in https://github.com/actions/cache/issues/810.
I have performed extensive testing on the new downloader and comparing to the existing downloader. Here's a week's worth of 99th percentile data showing that the old method is significantly more impacted by Azure Blob issues:
Due to a few more connection caching optimizations I made, we can also see by putting percentiles on the x-axis that total …
> Add option for concurrent cache downloads with timeout

- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/shared/config.ts
- packages/artifact/src/internal/upload/blob-upload.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
- packages/artifact/src/internal/upload/zip.ts
Tracking: https://github.com/github/c2c-actions-checks/issues/1699
This builds up on the work that was done in https://github.com/actions/toolkit/pull/1479,  https://github.com/actions/toolkit/pull/1481, https://github.com/actions/toolkit/pull/1486  and https://github.com/actions/toolkit/pull/1487
This PR adds zip creation + upload functionality to the upcoming v2.0.0 version of `@actions/artifact`. This in turn will power new v4 versions of `upload-artifact` and `download-artifact`.
Uploads should be significantly faster compared to the v1-v3 versions of upload-artifact since there is no proxying now and we can directly upload to blob storage from the runner. This should also make uploading less error-prone as the entire flow has been simplified.
We're also zipping without creating any …
> [Artifacts] zip creation + blob storage upload functionality

- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/upload/blob-upload.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
- packages/artifact/src/internal/upload/zip.ts
Tracking: https://github.com/github/c2c-actions-checks/issues/1699
This builds up on the work that was done in https://github.com/actions/toolkit/pull/1479, https://github.com/actions/toolkit/pull/1481, https://github.com/actions/toolkit/pull/1486 and https://github.com/actions/toolkit/pull/1487 and https://github.com/actions/toolkit/pull/1488
We want to save a hash of the artifact upload for integrity. Unfortunately the response from `uploadStream` does not have an MD5 hash value. There is a crc64 value in the raw headers but it doesn't appear to be officially documented in the azure blob NPM package so we're not going to try to use it as a result.
We can't also call `blobClient.properties` to get a hash after the upload finished since the token only has permissions to create and write, …
> [Artifacts] Save md5 hash for each artifact upload

- packages/core/src/oidc-utils.ts
oidc utils attempts to reference `error.results.message` instead of `error.message` when encountering a failure.  This PR corrects that.
> Fix error message reference in oidc utils

- .github/workflows/codeql.yml
Currently we're using v1, and there have been some important changes since then.
In particular, the latest version, v2.14.6, contains an important security patch:
> The CodeQL CLI no longer supports the `SEMMLE_JAVA_ARGS` environment variable. All previous versions of the CodeQL CLI perform command substitution on the `SEMMLE_JAVA_ARGS` value (for example, replacing `'$(echo foo)'` with `'foo'`) when starting a new Java virtual machine, which, depending on the execution environment, may have security implications. Users are advised to check their environments for possible `SEMMLE_JAVA_ARGS` misuse.
See the [codeql-cli-binaries release notes](https://github.com/github/codeql-cli-binaries/releases/tag/v2.14.4) for full details.
> Upgrade codeql actions to v2

- packages/github/RELEASES.md
- packages/github/__tests__/github.proxy.test.ts
- packages/github/__tests__/github.test.ts
- packages/github/__tests__/proxy.d.ts
- packages/github/package-lock.json
- packages/github/package.json
- packages/github/src/internal/utils.ts
- packages/github/src/utils.ts
Update octokit dependencies in github package.
According to octokit [docs](https://github.com/octokit/octokit.js#proxy-servers-nodejs-only) to use proxy we need to start using custom fetch function. This functionality was implemented in new `@actions/http-client`. 
As usage of fetch function is new logic, and octokit update has breaking changes, I bumped major version of github package. After this update github package will be able to use only with node>=18
I tested this change with `checkout` action: https://github.com/actions/checkout/pull/1504
> Update dependencies in github package

- package-lock.json
- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/src/internal/upload/blob-upload.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Recent MSFT guidance is to not use MD5, even for integrity. This updates the upload response to use SHA256 instead.
Related:
- https://github.com/github/actions-results-team/issues/1907
> Use sha256 instead of md5 for artifact v4 integrity hash

- package-lock.json
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/shared/config.ts
- packages/artifact/src/internal/shared/interfaces.ts
- packages/artifact/src/internal/upload/blob-upload.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
- packages/artifact/src/internal/upload/zip.ts
Some additional tweaks to help upload speeds in v4:
- Adjust concurrency based on number of CPUs (following [azcopy's formula](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize))
- Sets the `highWaterMark` for archiver to use the same other streams.
- Ability to tweak compression levels (zlib) to fit use case.
We'll expose a new input called `compression-level` on artifact upload.
For a random 4GB binary file with (compression-level: 0), this brought the upload time down from 3m+ to ~48s.
ℹ️ This also fixes a small bug with URL construction for the twirp client.
> Increase Artifact v4 upload speed

- packages/github/src/context.ts
This PR add GITHUB_RUN_ATTEMPT to `@actions/github` Context class.
I need to retrieve the `RUN_ATTEMPT` variable in order to retrieve some informations from my jobs using Octokit, like so:
```typescript
const jobs = await octokit.paginate(octokit.rest.actions.listJobsForWorkflowRunAttempt, {
owner: github.context.repo.owner,
repo: github.context.repo.repo,
run_id: github.context.runId,
attempt_number: github.context.runAttempt, // Missing :'(
});
```
> Add RUN_ATTEMPT to `@actions/github` Context class

- packages/artifact/__tests__/artifact-http-client.test.ts
- packages/artifact/__tests__/common.test.ts
- packages/artifact/__tests__/common.ts
- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/__tests__/path-and-artifact-name-validation.test.ts
- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/__tests__/upload-zip-specification.test.ts
- packages/artifact/__tests__/util.test.ts
- packages/artifact/package.json
- packages/artifact/src/generated/results/api/v1/artifact.ts
- packages/artifact/src/generated/results/api/v1/artifact.twirp.ts
- packages/artifact/src/internal/client.ts
- packages/artifact/src/internal/download/download-artifact.ts
- packages/artifact/src/internal/find/get-artifact.ts
- packages/artifact/src/internal/find/list-artifacts.ts
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/shared/interfaces.ts
- packages/artifact/src/internal/shared/util.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Part of:
- https://github.com/github/actions-results-team/issues/2038
For list/get/download operations, we'll use the internal runtime JWT and validate the claims to determine artifact resource access & fetch internally. This is a minor improvement so that `actions:read` permissions (not default) are not required to get/list/download Artifacts that currently scoped to the current run. This is the same behavior to how lookups on Artifacts work today.
In the future, it'd be great if we can solely rely on public APIs with new fine grained `GITHUB_TOKEN` permissions, but there are other efforts blocking it at this time.
We'll still offer the ability to use the public API for convenience, each of the Artifact client methods has `options` which has an intersection type with `FindOptions`: …
> Implement internal APIs for list/get/download artifacts

- packages/artifact/__tests__/get-artifact.test.ts
- packages/artifact/__tests__/list-artifacts.test.ts
- packages/artifact/src/generated/results/api/v1/artifact.ts
- packages/artifact/src/internal/client.ts
- packages/artifact/src/internal/find/get-artifact.ts
- packages/artifact/src/internal/find/list-artifacts.ts
- packages/artifact/src/internal/shared/interfaces.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Follow up to:
- https://github.com/actions/toolkit/pull/1591
Changes the behavior of get/list operations slightly. Also adds tests for these methods.
In the case of reruns (both full and partial) where there are Artifacts with the _same name_, the default behavior can be confusing.
The changes are as following:
1. For `getArtifact` if there are multiple with the same name, it will return the first.
2. For `listArtifacts` there is a new `options.latest` parameter that will filter the Artifacts to the latest by their name. This will be `true` for it's usage in `@actions/download-artifact@v4`. That way on rerun, it won't re-download past runs artifacts, only if the current run _doesn't_ have any for that name.
> Additional get/list artifact updates

- .github/workflows/artifact-tests.yml
- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/__tests__/get-artifact.test.ts
- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/src/artifact.ts
- packages/artifact/src/internal/client.ts
- packages/artifact/src/internal/download/download-artifact.ts
- packages/artifact/src/internal/find/get-artifact.ts
- packages/artifact/src/internal/shared/errors.ts
- packages/artifact/src/internal/shared/interfaces.ts
- packages/artifact/src/internal/upload/blob-upload.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Partially addresses:
- https://github.com/github/actions-results-team/issues/1805
For our artifact operations, we weren't being consistent on how we were surfacing errors. Sometimes we'd resolve with a response object of `{success:false}` or we'd reject via an error throw.
This PR changes the behavior so that the errors consistently throw/reject for promises to "bubble up" and don't require a bunch of `if(success) { }` logic. Any common errors are exposed that support additional debugging information.
Also, the workflow tests used for this package were updated to reflect these changes.
> Consistent error behavior for Artifact methods

- .github/workflows/artifact-tests.yml
- packages/artifact/CONTRIBUTIONS.md
- packages/artifact/README.md
- packages/artifact/RELEASES.md
- packages/artifact/docs/docs.md
- packages/artifact/docs/faq.md
- packages/artifact/src/artifact.ts
- packages/artifact/src/internal/client.ts
- packages/artifact/src/internal/shared/errors.ts
- packages/artifact/src/internal/shared/interfaces.ts
This starts the initial documentation for `@action/artifact` v2.
I'll be following up in another PR with autogenerated markdown docs for the functions, interfaces, etc.
Also, this change alters the export behavior of the default client.
Instead of:
```js
import * as artifact from '@actions/artifact'
const artifactClient = artifact.create()
artifact.getArtifact( /* ... */ )
```
Now there is a default export with the client already initialized:
```js
import artifact from '@actions/artifact'
artifact.getArtifact( /* ... */ )
```
> @actions/artifact doc updates

- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Fixes a bug where an error response causes the actions to hang for ~2 min.
Using [`why-is-node-running`](https://www.npmjs.com/package/why-is-node-running) we were able to track down the `ZLIB`, `TCPWRAP`, and `TLSWRAP` handlers clogging things up.
tl;dr
1. ZIP stream was being created way too early, we encounter an error & throw (reject) and the stream just hangs around.
2. In our retry http wrapper, we weren't reading the body on the request if it's a non-200 status code. For some reason (more investigation needed) this keeps things going until the keep-alive is met for the request? (or some other 2 minute timeout)
> Cleanup artifact handlers hanging node process

- packages/artifact/src/internal/shared/artifact-twirp-client.ts
We are returning a [429 Status code in our Twirp handlers](https://github.com/twitchtv/twirp/blob/206451d552e13701fa1111430aa81235029cb329/errors.go#L216). We shouldn't be retrying when we come across a 429.
> Remove 429 request from list of retry-able status codes

- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/download/download-artifact.ts
Unfortunately the `unzipper` library we first chose has some issues with node > 18:
- https://github.com/ZJONSSON/node-unzipper/issues/271
- https://github.com/ZJONSSON/node-unzipper/issues/286
So we're replacing with `unzip-stream`. In the future we may want to invest more changes into this, and keep track of a more maintained unzip library. Unfortunately there aren't a lot of great options that also stream the contents without writing the entire archive to disk:
- https://github.com/go-task/go-npm/issues/7#issuecomment-1568567117
Closes:
- https://github.com/github/actions-results-team/issues/2096
Example run:
- https://github.com/robherley/tmp-artifacts/actions/runs/7169128021
> [artifact] replace unzipper with unzip-stream

- packages/artifact/__tests__/artifact-http-client.test.ts
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/shared/errors.ts
- packages/artifact/src/internal/upload/blob-upload.ts
Will help customers debug network failures with self hosted runners faster.
Example error text would be:
> Failed to CreateArtifact: Unable to make request: ENOTFOUND
> If you are using self-hosted runners, please make sure your runner has access to all GitHub endpoints: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github
Closes: https://github.com/github/actions-results-team/issues/1805
> Add specific messages for network-specific node error codes

- packages/artifact/__tests__/artifact-http-client.test.ts
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
- packages/artifact/src/internal/shared/errors.ts
If customers encounter storage quota limits, they'll hit an error when trying to create artifacts.
This'll make the error more useful for the customers:
> Failed to CreateArtifact: Artifact storage quota has been hit. Unable to upload any new artifacts. Usage is recalculated every 6-12 hours.
> More info on storage limits: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#calculating-minute-and-storage-spending
Let me know if there's any other context we'd like to add to the message 👍
> Better error message for artifact usage limits

- packages/artifact/README.md
The instructions for the default export don't work for es modules (`.mjs`) files, so lets instruct users to just import the default client and instantiate instead.
Moving to `"type": "module"` is not something we want to commit to yet for `@actions/artifact`
Addresses:
- https://github.com/actions/toolkit/issues/1606
> Update artifact module quick start

- packages/core/README.md
Resolves #1559 
Adds missing documentation for the `summary` methods in `core`.
> Add missing actions/core documentation for job summaries

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
Adds a fix for transient request timeouts
Related to https://github.com/actions/download-artifact/issues/249
> Updating artifacts (download-artifact related) release notes

- packages/cache/src/internal/cacheHttpClient.ts
Previous to commit b2d865f18051, code used `components = paths.concat(...)`, which left `paths` unchanged.
The commit changed to using `components = paths`, then pushing onto `components` later.  This changes the `paths` array.
Closes #1377
> cache - getCacheVersion - dup paths array

- .github/workflows/artifact-tests.yml
- packages/artifact/README.md
- packages/artifact/__tests__/delete-artifacts.test.ts
- packages/artifact/src/generated/results/api/v1/artifact.ts
- packages/artifact/src/generated/results/api/v1/artifact.twirp.ts
- packages/artifact/src/internal/client.ts
- packages/artifact/src/internal/delete/delete-artifact.ts
- packages/artifact/src/internal/shared/interfaces.ts
Having official client methods to delete artifacts will make some use cases much simpler.
For instance, this could allow the ability to overwrite an artifact eventually in actions/upload-artifact.
e.g.
```yaml
- uses: actions/upload-artifact@v4
with:
name: my-artifact
path: path/to/artifact/
overwrite: true # something like this
```
Where overwrite would delete an artifact first, allowing for the upload of another.
I'll update the documentation in a separate PR.
Closes: https://github.com/actions/toolkit/issues/380
Partially supports: https://github.com/actions/upload-artifact/issues/471
> Add methods to delete artifacts

- packages/artifact/src/internal/find/get-artifact.ts
We want to be more descriptive in the reason why users might experience an artifact not being found. This error message update helps direct users to troubleshoot using the FAQ docs and common reasons for this issue. 
Updating the `ArtifactNotFoundError` in `getArtifactPublic` and `getArtifactInternal` to include more information.
Use the updated toolkit in a workflow using an outdated artifact or an artifact uploaded using a previous version. Expect the new error message.
> updating artifact not found error message

- packages/artifact/RELEASES.md
- packages/artifact/docs/generated/README.md
- packages/artifact/docs/generated/classes/ArtifactNotFoundError.md
- packages/artifact/docs/generated/classes/DefaultArtifactClient.md
- packages/artifact/docs/generated/classes/FilesNotFoundError.md
- packages/artifact/docs/generated/classes/InvalidResponseError.md
- packages/artifact/docs/generated/classes/NetworkError.md
- packages/artifact/docs/generated/classes/UsageError.md
- packages/artifact/docs/generated/interfaces/Artifact.md
- packages/artifact/docs/generated/interfaces/ArtifactClient.md
- packages/artifact/docs/generated/interfaces/DeleteArtifactResponse.md
- packages/artifact/docs/generated/interfaces/DownloadArtifactOptions.md
- packages/artifact/docs/generated/interfaces/DownloadArtifactResponse.md
- packages/artifact/docs/generated/interfaces/FindOptions.md
- packages/artifact/docs/generated/interfaces/GetArtifactResponse.md
- packages/artifact/docs/generated/interfaces/ListArtifactsOptions.md
- packages/artifact/docs/generated/interfaces/ListArtifactsResponse.md
- packages/artifact/docs/generated/interfaces/UploadArtifactOptions.md
- packages/artifact/docs/generated/interfaces/UploadArtifactResponse.md
- packages/artifact/package.json
Prepping for 2.1.0 release, will probably wait to include this PR too:
- https://github.com/actions/toolkit/pull/1628
> v2.1.0 Generate docs + update release notes

- packages/artifact/docs/faq.md
We now have FAQ docs on upload/artifact and download/artifact version compatibility and retention.
We want to hyperlink to these Question+Answers in the index section. 
If you have any edits to the updated sections, also please include those in this PR review!
> adding hyperlinks for new section of artifacts faq

- packages/artifact/__tests__/config.test.ts
- packages/artifact/src/internal/shared/config.ts
- packages/cache/__tests__/cacheUtils.test.ts
- packages/cache/src/internal/cacheUtils.ts
Currently, we are only checking equality against `github.com` to ensure artifact and cache actions are being run in a non-enterprise host. We need to update this check to allow requests from `ghe.com` and `ghe.localhost`, additional allowed hostnames for production and local development. 
Fixes https://github.com/github/actions-results-team/issues/2208
- We are including the known GItHub hostnames in the _negative_ condition for `isGhes`
- Run upload or download artifact from an allowed host using this toolkit package version
> Update GHES host check

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
We updated the `isGhes` check for `@actions/artifact` in https://github.com/actions/toolkit/pull/1648 and want to release a new version with this change
> updating artifact version and release to include ghes check change

- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
We updated the `isGhes` check for `@actions/artifact` in https://github.com/actions/toolkit/pull/1648 and want to release a new version with this change
> updating cache version and release to include ghes check change

- .github/workflows/audit.yml
- .github/workflows/cache-tests.yml
- .github/workflows/codeql.yml
- .github/workflows/releases.yml
- .github/workflows/unit-tests.yml
- .github/workflows/update-github.yaml
- docs/action-types.md
- docs/container-action.md
v3 actions run on node16 which will be deprecated. We should move to the latest and greatest
> Update workflows to use v4 actions

- packages/artifact/src/internal/download/download-artifact.ts
We have gotten reports of errors using the latest download-artifact@main:
```
##[debug]Failed to download artifact after 5 retries due to Callback called multiple times. Retrying in 5 seconds...
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not …
```
> Ensure callback is only called once

- CODEOWNERS
- README.md
- package-lock.json
- packages/attest/LICENSE.md
- packages/attest/README.md
- packages/attest/RELEASES.md
- packages/attest/__tests__/__snapshots__/intoto.test.ts.snap
- packages/attest/__tests__/__snapshots__/provenance.test.ts.snap
- packages/attest/__tests__/index.test.ts
- packages/attest/__tests__/intoto.test.ts
- packages/attest/__tests__/provenance.test.ts
- packages/attest/__tests__/sign.test.ts
- packages/attest/__tests__/store.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/attest.ts
- packages/attest/src/endpoints.ts
- packages/attest/src/index.ts
- packages/attest/src/intoto.ts
- packages/attest/src/provenance.ts
- packages/attest/src/shared.types.ts
- packages/attest/src/sign.ts
- packages/attest/src/store.ts
- packages/attest/tsconfig.json
Introduces a new `@actions/attest` package to support the creation of artifact attestations from GitHub Actions.
Exposes the `attest` and `attestProvenance` helper functions.
[Docs](https://github.com/actions/toolkit/blob/bdehamer/attest/packages/attest/README.md)
> add new @actions/attest package

- .github/workflows/releases.yml
Updates the `releases` workflow to publish npm packages with build provenance information.
The build provenance attestation will be attached the package and can be verified with the `npm audit signatures` command.
Packages published with provenance also get a badge like this when viewed on the npmjs registry.
See https://docs.npmjs.com/generating-provenance-statements
> publish npm packages with build provenance

- packages/attest/package-lock.json
- packages/attest/package.json
Updating the version for the `@actions/attest` package to 1.0.0 before initial publish.
> bump @actions/attest to 1.0.0

- packages/artifact/RELEASES.md
To make dependabot updates more useful and actionable, we're flipping the order of RELEASES.md
> Flip releases order

- packages/http-client/__tests__/keepalive.test.ts
- packages/http-client/src/index.ts
Starting with Node.js v19, http(s) `globalAgent` now uses `keep-alive` by default. The current `HttpClient` implementation uses `globalAgent` when `RequestOptions.keepAlive` is set to `false` (default), which is fine for `node16` runtime but incorrect for `node20`.
This PR fixes `HttpClient` to use a custom agent regardless of `RequestOptions.keepAlive` so that the option works correctly on both runtimes.
- [Node.js v19.9.0 documentation | `http.globalAgent`](https://nodejs.org/docs/latest-v19.x/api/http.html#httpglobalagent)
- https://github.com/nodejs/node/pull/43522
> Make sure RequestOptions.keepAlive is applied properly on node20 runtime

- packages/artifact/RELEASES.md
- packages/cache/RELEASES.md
Flipping `RELEASES.md` order for cache so it's easier to tell what changed via Dependabot. Additionally adding a release note to artifacts.
> Flip releases update order

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/download/download-artifact.ts
Adding info level logging for extraction provides more clarity to end users on what is being extracted.
> Add info level logging for zip extract

- packages/cache/__tests__/cacheHttpClient.test.ts
Hi @bethanyj28 - this is just the (tiny) test from [this PR](https://github.com/actions/toolkit/pull/1587). I couldn't reopen the PR due to permissions, so I made a new one.
> fix #1579: add test to check getCacheVersion does not mutate arguments

- package-lock.json
- packages/attest/README.md
- packages/attest/RELEASES.md
- packages/attest/__tests__/__snapshots__/intoto.test.ts.snap
- packages/attest/__tests__/__snapshots__/provenance.test.ts.snap
- packages/attest/__tests__/intoto.test.ts
- packages/attest/__tests__/oidc.test.ts
- packages/attest/__tests__/provenance.test.ts
- packages/attest/__tests__/store.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/oidc.ts
- packages/attest/src/provenance.ts
Updates the `attestProvenance` function in the `@actions/attest` package so that the provenance statement is populated from data read from a verified GHA OIDC token.
Previously, the provenance data was read directly from the environment. With the new approach, an OIDC token is retrieved from the GHA issuer and the provenance statement is built from the claims present in that token. This more closely mirrors the approach that is used by Sigstore certificate authority (Fulcio) when it populates the claims in the signing certificate.
> (@actions/attest) build provenance statement from OIDC claims

- packages/attest/RELEASES.md
- packages/attest/__tests__/sign.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/attest.ts
- packages/attest/src/sign.ts
Updates the `@actions/attest` package to generate attestations using a new version (v0.3) Sigstore bundle format. This new format includes a new media type ("application/vnd.dev.sigstore.bundle.v0.3+json") and some structural changes to the way that the signing certificate is represented.
Includes updates to two dependent packages:
* Bump `@sigstore/bundle` from 2.2.0 to 2.3.0
* Bump `@sgistore/sign` from 2.2.3 to 2.3.0
> (@actions/attest) generate attestations using v0.3 bundle format

- .github/CONTRIBUTING.md
- package-lock.json
- package.json
We are failing npm validation because of https://github.com/advisories/GHSA-f5x3-32g6-xq36. We are updating the dependent package to fix this vulnerability. 
This is marked as a breaking change in `npm audit`:
```
npm WARN audit Updating lerna to 6.4.1, which is a SemVer major change.
``` 
We use [lerna for package management](https://github.com/actions/toolkit/blob/9ddf153e007b587270658b32cc50a457e959c02c/.github/CONTRIBUTING.md?plain=1#L22). I've run the following scripts to verify this update does not break our usage: 
```
npm run audit-all
npm run bootstrap
npm run build 
npm run clean 
npm run repair 
npm run new-package [test]
```
I'm also updating the outdated instruction for running `new-package` so that it is clear for future contributors.
> fixing https://github.com/advisories/GHSA-f5x3-32g6-xq36

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/artifact-http-client.test.ts
- packages/artifact/package.json
- packages/artifact/src/internal/shared/artifact-twirp-client.ts
Occasionally the upstream artifact client may not respond in time (or other intermittent issues) so the GLB will respond with a 502 and a generic HTML response. We currently throw for non-JSON data as a response.
This tiny change allows us to retry in that scenario.
e.g.
- https://github.com/actions/upload-artifact/issues/543
> artifact client: retry on non-JSON response

- packages/attest/RELEASES.md
- packages/attest/__tests__/provenance.test.ts
- packages/attest/__tests__/store.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/store.ts
Removes the dependency on the `make-fetch-happen` library.
Previously, `make-fetch-happen` was being used as the fetch client to ease the process of mocking requests for the associated unit tests. This PR uses a new approach to mock the interaction with the GH API, so we no longer need this library.
> (@actions/attest) remove dep on make-fetch-happen

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/download/download-artifact.ts
This updates the `unzip-stream` dependency and goes back to using `unzip.Extract` over `unzip.Parse`.
> Use latest `unzip-stream` and `unzip.Extract`

- packages/attest/RELEASES.md
- packages/attest/__tests__/store.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/store.ts
Updates the attestations API client to be more resilient to intermittent errors.
Enables the `@octokit/plugin-retry` plugin for the Octokit client and configures a (default) retry count of 3. Any attempt to persist the generated attestation which results in a 5XX error will be retried up to 3 times (with [exponential backoff](https://github.com/octokit/plugin-retry.js/blob/v6.0.1/src/error-request.ts#L13)).
> (@actions/attest) retry request on failure to save attestation

- packages/attest/README.md
Adds a link to the GH docs from the `@actions/attest` README
> Update @actions/attest README

- packages/attest/__tests__/endpoints.test.ts
- packages/attest/__tests__/provenance.test.ts
- packages/attest/src/endpoints.ts
Instead of having the urls hardcoded, read them from the environment. I opted to read from the environment variable instead of the github context because it would be easier to test.
> Read the server url from the environment variable.

- packages/attest/RELEASES.md
- packages/attest/package-lock.json
- packages/attest/package.json
Bumps the version number of `@actions/attest` in preparation for a new release.
Includes the following dependency updates:
* Bump `@sigstore/bundle` from 2.3.0 to 2.3.2
* Bump `@sigstore/sign` from 2.3.0 to 2.3.2
> (@actions/attest) prepare 1.3.0 release

- package-lock.json
- packages/artifact/RELEASES.md
- packages/artifact/__tests__/config.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/shared/config.ts
Reduces friction of local development by allowing `*.localhost` domains for hostname checks. These were failing fast by the GHES hostname checker.
> Allow localhost hostnames for artifact checks

- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/src/internal/shared/config.ts
- packages/artifact/src/internal/upload/blob-upload.ts
While looking at [CI output](https://github.com/actions/toolkit/actions/runs/10057662696/job/27819363234?pr=1771#step:7:324) for:
- https://github.com/actions/toolkit/pull/1771
We had an issue/race where we were trying to do stuff _after_ the test completed:
> ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From packages/artifact/__tests__/upload-artifact.test.ts.
Turns out we had a few errors in our tests and I also discovered we were not handling our timeout logic correctly:
The problematic area of the timeout logic was that it was throwing an error within the `setTimeout` block, which is outside the promise area and went unhandled. To remedy this (and avoid other leaky async code) I swapped it with a `setInterval` wrapped in a Promise …
> Fix artifact upload chunk timeout logic + update tests

- packages/attest/RELEASES.md
- packages/attest/__tests__/oidc.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/oidc.ts
As part of the provenance generation logic, an OIDC token is retrieved from the GHA issuer in order to populate the claims in the attestation. The process of verifying the OIDC token requires that the JSON Web Key Set (JWKS) for the GHA OIDC issuer is retrieved. The library (`jwks-rsa`) we were using to retrieve the key set was not respecting the proxy settings of the actions runner. If a user was using a self-hosted runner behind a proxy the request to retrieve the JWKS would fail.
This change re-implements the JWKS look-up to use the `@actions/http-client` library for the retrieval -- this library has [proxy support](https://github.com/actions/toolkit/tree/main/packages/http-client#features) already included.
Per: https://github.com/actions/attest-build-provenance/issues/156
> fix proxy support for jwks retrieval

- packages/artifact/src/internal/upload/zip.ts
Fixes https://github.com/actions/upload-artifact/issues/485.
[The `.file` method](https://www.archiverjs.com/docs/archiver/#file) uses "a [lazystream](https://github.com/jpommerening/node-lazystream) wrapper to prevent issues with open file limits", which is precisely the scenario we're running into with https://github.com/actions/upload-artifact/issues/485.
This was originally part of https://github.com/actions/toolkit/pull/1723, but I pulled the bugfix out into its own PR so it can be reviewed separately from the bugfix that https://github.com/actions/toolkit/pull/1723 was for (preserving Unix file permissions in uploaded .zip files). This one is more urgent than the Unix file permissions, which can be worked around by uploading a .tar file.
> Prevent "too many open files" in artifact upload

- packages/artifact/src/internal/shared/config.ts
As mentioned in https://github.com/actions/upload-artifact/issues/591, changes of https://github.com/actions/toolkit/pull/1774 changed the upload chunk timeout from 5 minutes to 30 seconds which leads some repos to `Error: Upload progress stalled.`
This PR reverts the timeout to its original value.
> refactor: set chunk timeout back to 5 minutes

- package-lock.json
- packages/http-client/__tests__/basics.test.ts
- packages/http-client/__tests__/headers.test.ts
- packages/http-client/__tests__/proxy.test.ts
This pr updates packages to address some audit concerns, and fixes the http-client tests that have started breaking due to endpoint changes.
> Fix HTTP client tests

- packages/glob/RELEASES.md
- packages/glob/__tests__/internal-globber.test.ts
- packages/glob/package-lock.json
- packages/glob/package.json
- packages/glob/src/internal-glob-options-helper.ts
- packages/glob/src/internal-glob-options.ts
- packages/glob/src/internal-globber.ts
This PR adds an option to the glob package to exclude hidden files. This includes:
1. Any directory starting with `.`
2. Any file starting with `.`
3. Any files within a directory starting with `.`
This currently *does not* check for the hidden attribute that can be set on Windows files. Based on the discussion in https://github.com/nodejs/node/issues/38809, this isn't natively supported in Node at the moment.
I'm open to working around that limitation, but the primary focus here is for files and directories that use the `.` naming convention.
> Add glob option to ignore hidden files

- packages/attest/README.md
- packages/attest/RELEASES.md
- packages/attest/__tests__/store.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/attest.ts
- packages/attest/src/store.ts
Updates the `attest` and `attestProvenance` functions to accept a new, optional `headers` parameter.
If supplied, any headers will be passed-along to the GH attestations API in addition to the required auth header.
> support for headers param in attest functions

- packages/http-client/__tests__/proxy.test.ts
- packages/http-client/src/proxy.ts
https://github.com/actions/toolkit/issues/1779
https://github.com/google-github-actions/auth/issues/429
Success test result:
> Handle Encoded URL for Proxy Username and Password in HTTP Client

- packages/http-client/RELEASES.md
- packages/http-client/package-lock.json
- packages/http-client/package.json
Looks like we missed the release notes for 2.2.1, so I added those as well.
> HTTP Client 2.2.2 Release

- packages/attest/RELEASES.md
- packages/attest/__tests__/__snapshots__/provenance.test.ts.snap
- packages/attest/__tests__/provenance.test.ts
- packages/attest/src/oidc.ts
- packages/attest/src/provenance.ts
Closes: https://github.com/actions/toolkit/issues/1795
Updates the attestation logic so that the default OIDC issuer is derived from the current GH tenant context. 
This change should mean that most callers can omit the `issuer` parameter when calling `buildSLSAProvenancePredicate`/`attestProvenance` and rely on the library to select the correct OIDC issuer.
> derive default OIDC issuer from current tenant

- .github/workflows/releases.yml
This will give each run a name to help devs understand at a glance which package was published when browsing https://github.com/actions/toolkit/actions/workflows/releases.yml instead of just seeing "Publish NPM" over and over.
> Include the package name in the Publish Workflow run

- packages/http-client/src/index.ts
Fixes: #1798 
Applies the correct encoding to the proxy auth token in the `HttpClient` class.
The `token` parameter to the `ProxyAgent` is used literally in the `Proxy-Authorization` header and needs to be encoded as a proper basic-auth value.
See: https://undici.nodejs.org/#/docs/api/ProxyAgent?id=example-basic-proxy-request-with-authentication
Note: I tried, but couldn't find any reasonable way to write a unit test for this change 😬
> fix encoding for proxy auth token

- packages/attest/RELEASES.md
- packages/attest/__tests__/oidc.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/oidc.ts
Fixes an issue when generating provenance statements for enterprise accounts using [customized OIDC issuer value](https://github.com/actions/attest-build-provenance/issues/222).
Previously, there was a strict comparison of the `iss` claim in the OIDC token to ensure that it originated from the GitHub Actions provider. However, this did not account for the fact that enterprise accounts may append their enterprise slug to the end of the standard issuer URL.
The comparison has been updated to check that the issuer URL _starts with_ a value that matches the GitHub provider.
See: https://github.com/actions/attest-build-provenance/issues/222
> [@actions/attest] Fix bug with customized OIDC issuer

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/__tests__/upload-zip-specification.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/upload/upload-zip-specification.ts
- packages/artifact/src/internal/upload/zip.ts
With the changes introduced in:
- https://github.com/actions/toolkit/pull/1771
Which was meant to resolve:
- https://github.com/actions/upload-artifact/issues/485
We introduced a new bug:
- https://github.com/actions/upload-artifact/issues/590
We had a slight regression with symlinks. The typical behavior is that they are auto-resolved and the contents of the zip are added at the link's location. With the lazy-stream wrapper being used, it did not resolve the symlinks.
This PR switches our `stat` to an `lstat`, and we can check for a symbolic link, then resolve it, when we add the file to the zip archive.
> Fix regression, auto readlink on symlinks again

- packages/core/RELEASES.md
- packages/core/package-lock.json
- packages/core/package.json
Releasing the changes from #1824 for `@actions/core`.
Once this is released, `@actions/cache` and `@actions/tool-cache` can be updated to point to this new version of `@actions/core` and fully remove their indirect dependency on `uuid`.
Supports #925
> Release `@actions/core v1.11.0`

- packages/core/RELEASES.md
I missed that #1551 was released as part of 1.11.0 when writing up the release notes in #1839
> Include #1551 in `@actions/core` 1.11.0 release notes

- packages/artifact/package-lock.json
- packages/artifact/package.json
Closes https://github.com/actions/toolkit/issues/1614
As far as I can tell, there is no need to actually have this dependency anymore, it should just use the native module instead. This trips up certain bundlers, probably because the package is not really correct - it refers to a `index.js` entrypoint that does not exist (I suspect node does some internal stuff for this??) - see https://www.npmjs.com/package/crypto?activeTab=code
> Use native `crypto` package from node

- packages/artifact/RELEASES.md
- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/artifact/src/internal/upload/zip.ts
After adding custom symlink logic in:
- https://github.com/actions/toolkit/pull/1830
We did not resolve relative symlinks properly with `readlink`, we should have been using `realpath` to resolve. Also updated tests to better capture this case.
Reported in:
- https://github.com/actions/upload-artifact/issues/590#issuecomment-2399714918
> Properly resolve relative symlinks

- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/sign.ts
Update Sigstore deps:
* Bump `@sigstore/sign` from version 2.3.2 to 3.0.0
* Bump `@sigstore/bundle` from version 2.3.2 to 3.0.0
> `@actions/attest`: bump @sigstore/sign from 2.3.2 to 3.0.0

- packages/cache/RELEASES.md
- packages/tool-cache/RELEASES.md
- https://github.com/actions/toolkit/issues/925
Documenting the changes from #1824 and #1842, which have not been released yet.
Then ensures that when we cut a release soon, the removal of `uuid` will be documented.
> Document unreleased changes in `cache` and `tool-cache`

- .github/workflows/releases.yml
- .github/workflows/unit-tests.yml
For the workflows which execute unit tests, bumps the macOS runner from `macos-latest` to `macos-latest-large` to work-around some test failures which are occurring in the `@actions/exec` package (see #1859)
> use macos-latest-large in test/release workflows

- packages/attest/README.md
- packages/attest/__tests__/attest.test.ts
- packages/attest/__tests__/intoto.test.ts
- packages/attest/__tests__/provenance.test.ts
- packages/attest/src/attest.ts
- packages/attest/src/intoto.ts
Updates the `attest` and `attestProvenance` functions to accept an array of subjects which can be added to a single attestation.
Previously, these functions accepted a single subject name and digest -- allowing the consumer to create an attested intoto statement for just a single subject. This change deprecates the `subjectName`/`subjectDigest` params in favor of a new `subjects` option which accepts an array of subjects.
> `@actions/attest`: Support multi-subject attestations

- packages/attest/RELEASES.md
Update releases notes for v1.5.0 release of `@actions/attest` package.
> `@actions/attest`: Release notes for v1.5.0 release

- packages/artifact/__tests__/upload-artifact.test.ts
- packages/artifact/src/internal/shared/interfaces.ts
- packages/artifact/src/internal/upload/upload-artifact.ts
Updates the `UploadArtifactResponse` object to include the SHA-256 digest of the artifact that was created.
Returning the digest value will make it easy to integrate with things like the `attest-build-provenance` and `attest-sbom` actions -- allowing users to easily create attestations for artifacts created with the `upload-artifact` action.
> return artifact digest on upload

- packages/artifact/RELEASES.md
- packages/artifact/docs/generated/README.md
- packages/artifact/docs/generated/classes/ArtifactNotFoundError.md
- packages/artifact/docs/generated/classes/DefaultArtifactClient.md
- packages/artifact/docs/generated/classes/FilesNotFoundError.md
- packages/artifact/docs/generated/classes/GHESNotSupportedError.md
- packages/artifact/docs/generated/classes/InvalidResponseError.md
- packages/artifact/docs/generated/classes/NetworkError.md
- packages/artifact/docs/generated/classes/UsageError.md
- packages/artifact/docs/generated/interfaces/Artifact.md
- packages/artifact/docs/generated/interfaces/ArtifactClient.md
- packages/artifact/docs/generated/interfaces/DeleteArtifactResponse.md
- packages/artifact/docs/generated/interfaces/DownloadArtifactOptions.md
- packages/artifact/docs/generated/interfaces/DownloadArtifactResponse.md
- packages/artifact/docs/generated/interfaces/FindOptions.md
- packages/artifact/docs/generated/interfaces/GetArtifactResponse.md
- packages/artifact/docs/generated/interfaces/ListArtifactsOptions.md
- packages/artifact/docs/generated/interfaces/ListArtifactsResponse.md
- packages/artifact/docs/generated/interfaces/UploadArtifactOptions.md
- packages/artifact/docs/generated/interfaces/UploadArtifactResponse.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
Prepare v2.2.0 release of `@actions/artifact` package:
* Bump version string in `package.json`
* Update `RELEASES.md`
* Regenerate docs (necessary to capture new `digest` field in `UploadArtifactResponse.md` interface)
> Prepare artifact release 2.2.0

- packages/artifact/__tests__/config.test.ts
- packages/artifact/src/internal/shared/config.ts
Make both upload concurrency and timeout settings configurable with env variables.
Concurrency setting can only be lowered with the env variable, the goal is not to increase performance, but to stabilize the upload process.
> Make both upload concurrency and timeout settings configurable with env variables.

- packages/tool-cache/RELEASES.md
- packages/tool-cache/package-lock.json
- packages/tool-cache/package.json
Supports https://github.com/actions/toolkit/issues/925
With this change, `uuid` is no longer a dependency of `@actions/tool-cache`.
> [tool-cache] Update `@actions/core` and prepare 2.0.2 release

- packages/http-client/package-lock.json
- packages/http-client/package.json
Impact
[Undici fetch() uses Math.random()](https://github.com/nodejs/undici/blob/8b06b8250907d92fead664b3368f1d2aa27c1f35/lib/web/fetch/body.js#L113) to choose the boundary for a multipart/form-data request. It is known that the output of Math.random() can be predicted if several of its generated values are known.
If there is a mechanism in an app that sends multipart requests to an attacker-controlled website, they can use this to leak the necessary values. Therefore, An attacker can tamper with the requests going to the backend APIs if certain conditions are met.
References
https://hackerone.com/reports/2913312
https://blog.securityevaluators.com/hacking-the-javascript-lottery-80cc437e3b7f
https://hackerone.com/reports/2913312
https://blog.securityevaluators.com/hacking-the-javascript-lo …
> Security patch: Update undici package to 5.25.5

- packages/cache/__tests__/restoreCacheV2.test.ts
- packages/cache/src/cache.ts
Fixes:
- https://github.com/actions/cache/issues/1552
In `restoreCacheV2`, we have an additional warning on miss which is not the same behavior we had in `restoreCacheV1`. This changes the warning message & annotation to a debug (in V1 [we didn't have anything](https://github.com/actions/toolkit/blob/340a6b15b5879eefe1412ee6c8606978b091d3e8/packages/cache/src/cache.ts#L148)).
> Cache miss as debug, not warning annotation

- packages/artifact/__tests__/config.test.ts
- packages/artifact/src/internal/shared/config.ts
Currently we set the default concurrency based on the number of CPUs in the system.  We have lowered it to 5 in some cases when `upload-artifact` action reported connectivity issues and we saw some improved stability, so making 5 the default.
> Default upload artifacts concurrency to 5

- packages/cache/__tests__/saveCacheV2.test.ts
- packages/cache/src/cache.ts
When we create cache entries, it's normal behavior for multiple jobs to "race" to create the same entry. In the cache v1 implementations, we suppressed these errors with just a normal `log` statement however in v2 we create an annotation with `warning` that is confusing folks.
Here's the v1 implementation:
https://github.com/actions/toolkit/blob/662b9d91f584bf29efbc41b86723e0e376010e41/packages/cache/src/cache.ts#L402-L425
In v2, our client throws an error for a failed request, so we need to wrap that in the `ReserveCacheError`. That ensures we only emit an `info` statement, not a `warning` annotation:
https://github.com/actions/toolkit/blob/662b9d91f584bf29efbc41b86723e0e376010e41/packages/cache/src/cache.ts#L564-L565
> cache: wrap create failures in ReserveCacheError

- packages/attest/RELEASES.md
- packages/attest/__tests__/__snapshots__/provenance.test.ts.snap
- packages/attest/__tests__/provenance.test.ts
- packages/attest/package-lock.json
- packages/attest/package.json
- packages/attest/src/provenance.ts
Updates the `buildSLSAProvenancePredicate` function in the `@actions/attest` package to populate the `workflow.ref` field from the `ref` claim in the OIDC token.
For most events which trigger a workflow run (`push`, `release`, `workflow_dispatch`, etc) this will have no impact on generated predicate statement. For other events which may be triggered from ref-less commits, this will ensure that the populated value more accurately reflects the state of the workflow run.
> set workflow.ref provenance field from ref claim

- packages/artifact/CONTRIBUTIONS.md
- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/__tests__/list-artifacts.test.ts
- packages/artifact/src/generated/results/api/v1/artifact.ts
- packages/artifact/src/internal/download/download-artifact.ts
- packages/artifact/src/internal/find/get-artifact.ts
- packages/artifact/src/internal/find/list-artifacts.ts
- packages/artifact/src/internal/shared/interfaces.ts
The Artifacts REST API and Twirp services now return a digest field, giving a SHA256 digest of whatever was uploaded to the service. 
This change (combined with the implementation on the `download-artifact` package, will allow end users to use this to perform a comparison of this digest against the downloaded artifact to validate the integrity of what was downloaded.
The intent here is that the `download-artifact` package can then use the digests from the list method to supply them to download only if the comparison is desired. That package can also decide on whether to end the workflow or warn.
> Compare Artifact Digests

- packages/artifact/src/internal/shared/interfaces.ts
Fixing mistake introduced in 2.3.0 release where the comment on the `expectedHash` property was incorrect.
> Fix comment on expectedHash

- packages/artifact/src/internal/upload/blob-upload.ts
With the introduction of digest validation on artifact download, taking this opportunity to change the message printed during upload to use the same terminology.
> Change hash to digest for consistent terminology across runner logs

- packages/cache/__tests__/restoreCacheV2.test.ts
- packages/cache/src/cache.ts
This changes adds additional logging information to the debug message returned when a cache restore request fails to find a matching key.
It adds the cache version requested as not only keys but also version must match for a cache restore to be successfully.
Logging the version will assist in troubleshooting cache restore failures.
> Log cache version requested on debugging message

- packages/artifact/RELEASES.md
- packages/artifact/package-lock.json
- packages/artifact/package.json
- packages/cache/RELEASES.md
- packages/cache/package-lock.json
- packages/cache/package.json
This pull request includes bumps to the `@actions/artifact` and `@actions/cache` packages. The changes primarily focus on version updates and adding masking for Secure Access Signatures (SAS) URLs.
* Added masking for Secure Access Signatures (SAS) artifact URLs to enhance security.
* Changed hash terminology to digest for consistent terminology across runner logs.
* Updated version number to `2.3.2` in `package.json`.
* Added masking for Secure Access Signatures (SAS) cache entry URLs to enhance security.
* Updated version number to `4.0.3` in `package.json`.
* Improved debugging by logging both the cache version and keys requested when a cache restore fails
> Prepare Cache v4.0.3 & Artifact v2.3.2 releases

- packages/cache/__tests__/__fixtures__/index.js
Closes https://github.com/actions/toolkit/issues/2042
Due to deprecation of ArtifactCache service, saveCacheV1 fails in production, and so the cache tests that use it fail. This addresses that.
> Fix cache tests

- packages/github/RELEASES.md
- packages/github/package-lock.json
- packages/github/package.json
Toolkit audit is failing due to some vulnerabilities in dependencies. This PR updates the dependencies to fix the vulnerabilities, starting with `github`, which we'll need to release to address the vulnerabilities in the other packages that depend on it.
> NPM Audit Fixes

- packages/github/RELEASES.md
- #1754
- https://github.com/actions/github-script/issues/566
#1588 added `context.runAttempt` but we never published a new version until yesterday 😄
> Document `context.runAttempt` in @actions/github 6.0.1

- packages/cache/__tests__/restoreCacheV2.test.ts
- packages/cache/src/cache.ts
Fixes: https://github.com/actions/cache/issues/1626
Improve logging for cache restoration in the `restoreCacheV2` functionality. It adds more specific log messages to differentiate between cache hits for exact keys and restore keys, enhancing debugging and traceability.
> Explicit logging of cache key and restore key matches

- packages/cache/package-lock.json
- packages/cache/package.json
Fixes: https://github.com/actions/toolkit/issues/2112
Related to: https://github.com/actions/toolkit/pull/2106
By moving `@protobuf-ts/plugin` from dependencies to devDependencies, `@protobuf-ts/runtime-rpc` which is a runtime dependency was lost.
This change reintroduced `@protobuf-ts/runtime-rpc` only and not the entire `@protobuf-ts/plugin` package which has 6 other dependencies not needed during runtime.
> Reintroduce `@protobuf-ts/runtime-rpc` as a runtime dependency

- .github/workflows/cache-tests.yml
- packages/cache/__tests__/saveCache.test.ts
The update ensures that only runtime dependencies are installed (excluding development dependencies) when compiling the cache package, which helps verify that the shipped package contains only what's needed for production.
Prevents a recurrence of: https://github.com/actions/toolkit/issues/2112
> Update cache package compilation step to only install runtime dependencies

- packages/cache/__tests__/saveCache.test.ts
- packages/cache/__tests__/saveCacheV2.test.ts
- packages/cache/src/cache.ts
- packages/cache/src/generated/results/api/v1/cache.ts
Remove size limit for individual caches on upload, allow for more specific error codes from results backend.
> Remove 10GB Cache Size Limit for Cache Service V2

- packages/artifact/src/internal/download/download-artifact.ts
Hi. There is a bug in the `actions/download-artifact` repository: https://github.com/actions/download-artifact/issues/396. The gist is that the artefact downloading is reported as successful on the download step, but further down, it is revealed that the artefact is corrupt/not present/not fully downloaded. And the downloading step does not report any logs/issues, the only logs are: 
```
Downloading single artifact
Preparing to download the following artifacts:
- fmod-project-build-16795056208 [redacted]
Redirecting to blob download url: [redacted]
Starting download of artifact to: /Users/effortstarbuild/runner/_work/[redacted]
(node:19985) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or …
```
> [ARTIFACT] Reject download promise if timeout was reached

- packages/artifact/__tests__/download-artifact.test.ts
- packages/artifact/src/internal/download/download-artifact.ts
This test will fail until we merge the changes in this [PR](https://github.com/actions/toolkit/pull/2124). I wanted to take the proposed changes there so I'm adding a test to be merged after the fact.
This should check that a hung stream will fail. I updated the code to make the timeout configurable so we're not waiting the full `30s`.
> Test: add a timeout test for downloading chunks from the stream
