actions/toolkit

docs/container-action.md
Quick typo fix in the `container-action.md` file.
=> container-action typo fix

packages/core/RELEASES.md, packages/exec/RELEASES.md, packages/github/RELEASES.md, packages/io/RELEASES.md, packages/tool-cache/RELEASES.md, packages/tool-cache/package-lock.json, packages/tool-cache/package.json
Once this is in, I'll publish the new tool-cache.
Resolves #66
=> Add RELEASES.md for each package, bump tool-cache to publish

docs/javascript-action.md
=> Need right push target

packages/tool-cache/README.md
Related to my research:
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
[Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
=> Don't recommend the use of HTTP to download code

docs/commands.md
=> Update command docs to specify a new line is needed

.github/workflows/workflow.yml, README.md, packages/exec/__tests__/exec.test.ts
=> fix test timeout

docs/commands.md
Added warning about registering multiline secrets
=> Add Warning about multiline secrets

.github/ISSUE_TEMPLATE/enhancement_request.md, docs/action-debugging.md, packages/github/README.md
Just fixes some documentation links. A few were broken and not pointing to the correct place anymore.
=> Fix documentation links

packages/exec/README.md
=> remove misleading verbiage

package-lock.json, package.json
=> fix errors during npm install

docs/github-package.md
The JavaScript Action Walkthrough has been moved to its own repository at https://github.com/actions/javascript-action
Resolves #241
=> Fix broken doc links

package-lock.json
This PR updates `package-lock.json` with changes generated by `npm audit fix`.
On a fresh clone of this repo at https://github.com/actions/toolkit/commit/a11539e1db495a98e3e8fd45249cc1e0ffddf1cd, changing directory into the repo and running `npm install` produces the following warning:
```
> npm i
> fsevents@1.2.11 install {redacted}
> node-gyp rebuild
SOLINK_MODULE(target) Release/.node
CXX(target) Release/obj.target/fse/fsevents.o
SOLINK_MODULE(target) Release/fse.node
added 1409 packages from 598 contributors and audited 930414 packages in 38.148s
found 9 high severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
```
Here's the output of `npm audit`:
<details>
```
=== npm audit security report === …
```
=> package-lock.json: update handlebars & uglify-js

.github/workflows/unit-tests.yml, package.json, packages/core/package.json, packages/exec/package-lock.json, packages/exec/package.json, packages/github/package.json, packages/glob/package-lock.json, packages/glob/package.json, packages/io/package-lock.json, packages/io/package.json, packages/tool-cache/package-lock.json, packages/tool-cache/package.json
We should run security audits as part of ci
See https://docs.npmjs.com/cli/audit
=> audit security vulnerabilities as part of ci

packages/core/package.json, packages/exec/package.json, packages/github/package.json, packages/io/package.json, packages/tool-cache/package.json
=> bump versions

packages/core/RELEASES.md, packages/exec/RELEASES.md, packages/github/RELEASES.md, packages/glob/RELEASES.md, packages/io/RELEASES.md, packages/tool-cache/RELEASES.md
=> release notes

packages/github/__tests__/lib.test.ts, packages/github/src/context.ts
=> Correctly pull issue number for pull request review events

packages/tool-cache/README.md
This adds two missing `await`s.
=> await tc.downloadTool

packages/tool-cache/README.md
Self-hosted runners are now available.
=> Update tool cache docs

docs/action-debugging.md, packages/core/README.md, packages/core/__tests__/core.test.ts, packages/core/src/core.ts
https://github.com/actions/runner/pull/253
https://github.com/actions/toolkit/pull/206
=> Add core.isDebug() to check whether actions_step_debug is on or not.

packages/core/RELEASES.md, packages/core/package-lock.json, packages/core/package.json
1.2.3 release with new core.IsDebug()
=> core 1.2.3 release

packages/artifact/CONTRIBUTIONS.md, packages/artifact/README.md, packages/artifact/docs/artifact-contributions.md
Some guidelines for how users can test large changes and what they should look out for.
https://github.com/actions/toolkit/issues/378
It's pretty much impossible to add end-to-end tests to upload/download artifacts after the package has been build because certain env variables are not exposed from the context of a shell.
Rendered contribution guidelines 🎨 [Rendered](https://github.com/actions/toolkit/blob/konradpabjan/artifact-contribution-guidelines/packages/artifact/CONTRIBUTIONS.md)🖌
=> Contribution guidelines for artifact package

docs/action-versioning.md
Per discussion with @joshmgross
=> Add a screenshot to release instructions

packages/core/RELEASES.md, packages/core/package-lock.json, packages/core/package.json
Bump @actions/core to 1.2.4 and add notes in preparation for release!
=> @actions/core 1.2.4 version bump and release notes

.github/workflows/audit.yml, .github/workflows/unit-tests.yml, README.md
Create a separate badge for audit
=> separate audit workflow

packages/tool-cache/package.json, packages/tool-cache/src/tool-cache.ts
1) Change downloadTool to support any auth header
2) Change getManifestFromRepo to accept any auth header (consistency within the module)
=> support any auth header

docs/commands.md
Now that the official docs for pre and post actions are up, we should link those in our save state docs!
=> Update Save State Docs

packages/cache/README.md
Part of https://github.com/actions/cache/issues/323
=> Update cache readme to include a link to cache action

.github/workflows/cache-tests.yml
Closes https://github.com/actions/toolkit/issues/485
=> Delete cache folders prior to restore in tests

LICENSE.md, packages/artifact/LICENSE.md, packages/cache/LICENSE.md, packages/core/LICENSE.md, packages/exec/LICENSE.md, packages/github/LICENSE.md, packages/glob/LICENSE.md, packages/io/LICENSE.md, packages/tool-cache/LICENSE.md
=> Add License.md to all npm packages

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
Update:
- RELEASES.md
- package.json
- package-lock.json
=> Release preparation of artifact 0.4.0

packages/core/RELEASES.md, packages/core/package-lock.json, packages/core/package.json
Release notes for `actions/core@1.2.6`
=> Actions core 1.2.6 release

docs/commands.md
Explain to the ignorant reader where this `STATE_` prefix comes from.
=> Explain to the ignorant reader where this `STATE_` prefix comes from.

packages/cache/RELEASES.md, packages/cache/__tests__/tar.test.ts, packages/cache/package-lock.json, packages/cache/package.json, packages/cache/src/internal/tar.ts
Fixes https://github.com/actions/cache/issues/527
=> Fix permissions issues using gtar on mac

docs/commands.md
=> docs: Fix two typos and add some blank lines to commands.md

packages/io/__tests__/io.test.ts, packages/io/src/io-util.ts, packages/io/src/io.ts
Copy of this pr: https://github.com/actions/toolkit/pull/444
Merged into the incorrect branch, so recreating the pr to merge
=> Simplify mkdirP implementation

docs/problem-matchers.md
Port of [this pr](https://github.com/actions/toolkit/pull/820) to the correct branch
=> Fix debug logging link (#820)

package.json
Adds a quick script to lint the packages
=> add the lint-fix script

packages/core/README.md, packages/core/RELEASES.md, packages/core/package-lock.json, packages/core/package.json, packages/glob/RELEASES.md, packages/glob/package-lock.json, packages/glob/package.json, packages/io/RELEASES.md, packages/io/package-lock.json, packages/io/package.json
Lets update the toolkit packages and publish new versions
- core
- glob
- io
We will update the tool-cache after the io release is finalized!
=> New versions of toolkit packages

package-lock.json, packages/core/RELEASES.md, packages/core/package.json
=> Update release for core 1.5.0

packages/artifact/package-lock.json, packages/artifact/package.json
`@types/tmp` is type definitions for `tmp`.
It is not needed in runtime, so it should be devDependencies.
=> artifact: @types/tmp should be devDependencies

CODEOWNERS
- Use the actions-cache team as owner of the [@actions/cache](https://github.com/actions/toolkit/blob/main/packages/cache) package.
- Use the artifacts-actions team as owner of the [@actions/artifact](https://github.com/actions/toolkit/blob/main/packages/artifact) package.
=> Update CODEOWNERS with new teams

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
https://github.com/github/c2c-actions-checks/issues/270
=> Update `lockfileVersion` for artifact package

packages/io/RELEASES.md, packages/io/package-lock.json, packages/io/package.json
Closes github/c2c-actions-checks#293
=> Update `lockfileVersion` in `package-lock.json` in `io` package

packages/glob/RELEASES.md, packages/glob/package-lock.json, packages/glob/package.json
Closes github/c2c-actions-checks#293
=> Update `lockfileVersion` in `package-lock.json` in `glob` package

packages/cache/RELEASES.md, packages/cache/package-lock.json, packages/cache/package.json
Closes github/c2c-actions-checks#293
=> Update `lockfileVersion` in `package-lock.json` in `cache` package

packages/cache/RELEASES.md, packages/tool-cache/RELEASES.md, packages/tool-cache/package-lock.json, packages/tool-cache/package.json
Closes github/c2c-actions-checks#293
=> Update `lockfileVersion` in `package-lock.json` in `tool-cache` package

packages/cache/__tests__/saveCache.test.ts, packages/cache/package-lock.json, packages/cache/src/cache.ts, packages/cache/src/internal/cacheHttpClient.ts, packages/cache/src/internal/cacheUtils.ts, packages/cache/src/internal/contracts.d.ts, packages/cache/src/internal/requestUtils.ts
=> Revert "T dedah/cache size"

packages/core/RELEASES.md, packages/core/package-lock.json, packages/core/package.json
=> `actions/core` 1.9.0 release

packages/cache/src/internal/downloadUtils.ts
- Reverted the abortController code as it aborts only when download is active.
- Added customPromise whose POC was done earlier, this is working as expected. Executed [workflow](https://github.com/bbq-beets/test-cache-load/actions/runs/2837529889) and [run](https://github.com/bbq-beets/test-cache-load/runs/7780730233?check_suite_focus=true#step:2:3627)
=> Implemented custom promise as abortController isn't able to stop the workflow in real scenarios

packages/core/README.md, packages/core/src/core.ts
=> Fix endColumn documentation

packages/cache/package-lock.json, packages/cache/package.json
=> Declare dependency on `@azure/abort-controller`

packages/cache/__tests__/tar.test.ts, packages/cache/src/internal/cacheUtils.ts, packages/cache/src/internal/constants.ts, packages/cache/src/internal/tar.ts
Reverts actions/toolkit#1232
These changes will be added to branch `releases/v3-beta`
=> Revert "Add GNUtar as default in windows"

packages/artifact/src/internal/upload-specification.ts
Fixes: https://github.com/actions/upload-artifact/issues/92
=> fix: use `stat` instead of `lstat`

docs/commands.md
This is described in documentation elsewhere.
=> Add documentation for notice

packages/cache/README.md
Update readme for latest cache release with info regarding
1. Segment size change
2. Default timeout change
=> Update README for latest cache release changes

packages/cache/package-lock.json
Updates some packages that have known vulnerablilities, so that the CI audit passes.
=> Update actions/cache dependencies to fix vulnerabilities

.github/workflows/artifact-tests.yml
These CI tests are used in addition to our jest unit-test to see how the node module behaves in an actions environment.
I've updated them slightly to include download tests too.
Follow up to this comment:
- https://github.com/actions/toolkit/pull/1594#discussion_r1417601789
=> Update artifact workflow tests

packages/cache/package.json
Release will include:
- https://github.com/actions/toolkit/pull/1378
Which will address:
- https://github.com/actions/toolkit/issues/1377
Will publish new version after this is merged
=> Update cache npm package version

packages/cache/RELEASES.md
For:
- https://github.com/actions/toolkit/pull/1622
- https://github.com/actions/toolkit/pull/1378
=> Updates release notes for @actions/cache v3.2.3

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
Updates package version + release notes.
=> Prep for @actions/artifact v2.1.9

packages/attest/RELEASES.md
Include PR links in the release notes for better visibility to specific code changes.
=> improve release notes for @actions/attest

packages/artifact/RELEASES.md
=> Update artifact release notes

packages/attest/RELEASES.md, packages/attest/package-lock.json, packages/attest/package.json
Update version and release notes for `@actions/attest@1.5.0`
=> `@actions/attest`: prep release of @actions/attest v1.5.0

packages/cache/RELEASES.md, packages/cache/package-lock.json, packages/cache/package.json
Supports https://github.com/actions/toolkit/issues/925
=> Prepare `@actions/cache` 3.3.0 release

packages/cache/src/generated/results/api/v1/cache.ts, packages/cache/src/generated/results/api/v1/cache.twirp.ts
`LookupCacheEntryRequest` is unused and doesn't need to be included in this package.
=> Remove unused cache API

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
Prep release packages/artifact v2.2.1 to include: #1928
=> Prep release packages/artifact v2.2.1

packages/cache/RELEASES.md, packages/cache/package-lock.json, packages/cache/package.json
Includes changes from:
- https://github.com/actions/toolkit/pull/1954
- https://github.com/actions/toolkit/pull/1947
- https://github.com/actions/toolkit/pull/1907
=> Update manifests & release notes for cache v4.0.1

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
=> Prepare artifact release 2.2.2

packages/attest/package-lock.json, packages/attest/package.json, packages/github/package-lock.json, packages/github/package.json, packages/http-client/package-lock.json, packages/http-client/package.json
Fixes: https://github.com/actions/toolkit/issues/1684
Handles the following issues:
* https://github.com/actions/toolkit/security/dependabot/70
* https://github.com/actions/toolkit/security/dependabot/69
* https://github.com/actions/toolkit/security/dependabot/53
* https://github.com/actions/toolkit/security/dependabot/52
* https://github.com/actions/toolkit/security/dependabot/47
* https://github.com/actions/toolkit/security/dependabot/43
* https://github.com/actions/toolkit/security/dependabot/67
=> Bump undici to v5.28.5

packages/artifact/src/internal/find/list-artifacts.ts
For loop was incrementing loop counter twice, this pr fixes that
=> Dont skip pages

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
Includes changes from [PR 1975](https://github.com/actions/toolkit/pull/1975)
=> Prepare for Artifact v2.3.0 release

packages/artifact/RELEASES.md, packages/artifact/package-lock.json, packages/artifact/package.json
Prepare for patch release 2.3.1 of `@actions/artifact`
=> Bump release version
